### ISSUE TITLE
No pop-up appears

### ISSUE THREAD

**Issue by bbrendon** [keesschollaart81/vscode-home-assistant#10]
I went to "file -> open folder". Selected my hass folder and nothing pops up.

I think the docs are missing something.

**Comment by bbrendon** [comment]
I never did find a pop-up but after playing around with things for awhile I finally decided it had something to do with workspaces so I tried it playing with that a bit and its magically working now.

I would write new docs but I don't really understand workspaces. I've always just used it as a generic editor.

**Comment by keesschollaart81** [comment]
That's interesting because is should show, even with the 'open folder' way. Do you have a configuration.yaml somewhere in that folder?

In any case, I updated the docs to be (hopefully) more clear on this, also pointing out it's as easy to set the configuration via the settings UI.

**Comment by bbrendon** [comment]
So it stopped working.... I had a window VS code window already open and then opened the HASS workspace and the extension wasn't working. Once I closed everything and started over with only the HASS workspace open it worked. I feel like there is something about vs code I don't understand but it seems like it should have worked.

Anyway. Thanks for the work on this. I'm hoping I can use it in appdaemon as well. I haven't tried. Fingers crossed :)

If you have any ideas as to what my problem is I'm all ears.
