### ISSUE TITLE
High CPU on macOS

### ISSUE THREAD

**Issue by agilljam** [keesschollaart81/vscode-home-assistant#103]
Process "Code helper" has very high CPU usage.

**Comment by Duncank** [comment]
Noticed that too; I've checked all my extensions, but narrowed it down to this one by disabling them one by one.

**Comment by keesschollaart81** [comment]
Is it while typing/changing code? What do you see in the log?

**Comment by oziee** [comment]
this is occurring in v1.20.. the Mac fan runs high 10sec after opening VS Code

this plugin is the cause and uses 100+% CPU

```
ps aux | grep 17491
17491 101.9  2.5  8831548 420220   ??  R    10:48am   0:43.02 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/xxxxxx/.vscode/extensions/keesschollaart.vscode-home-assistant-1.20.0/out/server/server.js --node-ipc --clientProcessId=17486
17518   0.0  0.0  4259000    260 s001  R+   10:49am   0:00.01 grep 17491
```

disabling this extension and restarting VSCode the problem is gone

**Comment by mwolter805** [comment]
Having the same issue with version 1.20 of the extension. Big Sur 11.2.3 and VS Code 1.58.2.

Narrowed it down to this process and disabling Home Assistant Config Helper resolved the issue. 
```
19621 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/mwolter/.vscode/extensions/keesschollaart.vscode-home-assistant-1.20.0/out/server/server.js --node-ipc --clientProcessId=19605
```
