### ISSUE TITLE
Feature request: Reload context menu

### ISSUE THREAD

**Issue by Fusseldieb** [keesschollaart81/vscode-home-assistant#105]
I miss this one thing. "Configurator" has a menu to reload all kinds of HA-related files, which VSCode totally lacks. This makes me switch back and forth between pages just to reload something.

![image](https://user-images.githubusercontent.com/4715129/65175307-0726ac00-da29-11e9-9cce-8b7d8fc8f540.png)

Would be awesome to see a (context) menu for those things in this Extension :)

**Comment by keesschollaart81** [comment]
Totally agree! Let's make this happen in the next version!

**Comment by keesschollaart81** [comment]
🎊
