### ISSUE TITLE
Support HASS_TOKEN and HASS_SERVER

### ISSUE THREAD

**Issue by maxandersen** [keesschollaart81/vscode-home-assistant#11]
https://github.com/home-assistant/home-assistant-cli Supports specifying server and its token via environment variables. Would be super nice if this extension would use these when the settings in vscode are blank. 

Then from terminal I could just use 'code configuration.yaml' and things would "just work" :)

**Comment by keesschollaart81** [comment]
Great idea! Implemented in v0.3!

**Comment by maxandersen** [comment]
I reset all the settings I could find then ran `code-insiders configuration.yaml` from terminal where HASS_SERVER/HASS_TOKEN is configured but when editing I see no autocompletion at all...is there a way to check why ? enable some logging or similar ?

**Comment by keesschollaart81** [comment]
With https://github.com/keesschollaart81/vscode-home-assistant/commit/3ca3590773ea02d56bf721f0adbdc979f9567547 it should now be visible in the log which settings are being read. If you start VS Code, click help > Toggle Developer Tools, check the Console tab. 

After you type ':' after a entity_id, the logging will hopefully give some insight in what's going on...

**Comment by keesschollaart81** [comment]
@maxandersen if this is still an issue, please reopen / comment!

**Comment by maxandersen** [comment]
will do - just travelling at the moment so can't verify yet.
