### ISSUE TITLE
YAMLSemanticError: Implicit map keys need to be followed by map values

### ISSUE THREAD

**Issue by denniswham** [keesschollaart81/vscode-home-assistant#117]
I do see the below error:

`File 'configuration.yaml' could not be parsed, it was referenced from path 'configuration.yaml'. This file will be ignored. Error(s): - YAMLSemanticError: Implicit map keys need to be followed by map values (Line: 82)`

A config check returns no erros, both checked that via the UI (Configuration / Server Control), and via SSH.

Can it be that the error is shown incorrectly?

**Comment by keesschollaart81** [comment]
It seems this is a bug coming from here: https://github.com/eemeli/yaml/issues/120
I've updated this package to 1.7.2 and then the bug will be fixed!
