### ISSUE TITLE
Cannot connect using windows 10

### ISSUE THREAD

**Issue by folrewef** [keesschollaart81/vscode-home-assistant#129]
I am sorry if I should not ask support questions here, but I try anyway:
When setting up I have a Long Lived Access Token that I have pasted
I try different url:s but none seems to work:

I try using both https and http with the same result.

examples:

https:\\hassio
https:\\192.168.1.119:8123
https:\\xxxxxxx.duckdns.org:8123

I get:

> Error connecting to your Home Assistant Server at https://192.168.1.119:8213 and token 'eyJ0e...', check your network or update your VS Code Settings, make sure to (also) check your workspace settings! Error: ERR_CANNOT_CONNECT

If I exclude https:/http: and write only \\hassio  I get

> (node:1904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

What do I do wrong?

**Comment by keesschollaart81** [comment]
Let's start with basics, can you open the Home Assistant UI in a browser on the same machine VS Code runs?

The second error I cannot understand what's going on. The first one seems to occur if you try to connect over http**s** where the certificate is invalid. Please try to check the 'Ignore Certificates' setting in the Home Assistant Settings section in VS Code or fix the certificate issue.

**Comment by folrewef** [comment]
Thanks for responding.

Yes - I can open the Home Assistan UI.

I have checked "Ignore certificates" without any change.

I also get this message:

[Auth Phase] Connecting to Home Assistant...
WebSocket Connection to Home Assistant closed with an error: Disconnected from Home Assistant with a WebSocket error with message: connect ECONNREFUSED 192.168.1.119:80

**Comment by dsyorkd** [comment]
I'm having the same issue, can connect to the url locally via the browser, but the extension fails with ERR_CANNOT_CONNECT

I have Ignore Certificates checked, and I created a new token to test with. 

Tried for Host Url:
https://10.100.1.200:8123
10.100.1.200:8123

I'm using VS-Code v 1.40.2 on MacOS 10.15.1

**Comment by folrewef** [comment]
I have made some progress but it still does not work. I no longer get ERR-CANNOT_CONNECT.

Instead I get the following error messages:

(node:13744) UnhandledPromiseRejectionWarning: Error: [UriError]: Scheme contains illegal characters. at _validateUri (c:\Users\Fredrik\.vscode\extensions\keesschollaart.vscode-home-assistant-1.4.5\node_modules\vscode-uri\lib\umd\index.js:68:19) at _URI.URI (c:\Users\Fredrik\.vscode\extensions\keesschollaart.vscode-home-assistant-1.4.5\node_modules\vscode-uri\lib\umd\index.js:157:17) at new _URI (c:\Users\Fredrik\.vscode\extensions\keesschollaart.vscode-home-assistant-1.4.5\node_modules\vscode-uri\lib\umd\index.js:359:51) at Function.URI.parse (c:\Users\Fredrik\.vscode\extensions\keesschollaart.vscode-home-assistant-1.4.5\node_modules\vscode-uri\lib\umd\index.js:269:20) at ConfigurationService.getUri (c:\Users\Fredrik\.vscode\extensions\keesschollaart.vscode-home-assistant-1.4.5\out\language-service\src\configuration.js:20:37) at ConfigurationService.updateConfiguration (c:\Users\Fredrik\.vscode\extensions\keesschollaart.vscode-home-assistant-1.4.5\out\language-...

(node:13744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:13744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have no clue as to what this means.
