### ISSUE TITLE
Error on all files in script dir

### ISSUE THREAD

**Issue by SteffenM-DE** [keesschollaart81/vscode-home-assistant#130]
Hi,

I suddenly get this error at the output of all yaml files in script directory:

File 'o:/scripts/hauptschalter_master_off.yaml' could not be parsed, it was referenced from path 'configuration.yaml/homeassistant/packages/script'. This file will be ignored. Error message: TypeError: source_utils_1.default is not a function Error(s): 
 - TypeError: source_utils_1.default is not a function

There is nothing special and working too:

`
script_hauptschalter_master_off:
  alias: Hauptschalter OFF
  sequence:
    - service: media_player.media_pause
      entity_id:
        - group.grp_sonosmedia
`

Regards, Steffen

**Comment by keesschollaart81** [comment]
Should be fixed with v1.3.1
