### ISSUE TITLE
Problem: Property "style" not allowed ui-lovelace.yaml

### ISSUE THREAD

**Issue by ekendra-nz** [keesschollaart81/vscode-home-assistant#132]
![11](https://user-images.githubusercontent.com/16280702/67859955-ab038b80-fb81-11e9-99d3-7917906ee7dc.JPG)

I get a persistant parse error as depicted in the image above.

Style is a property enabled by this card mod:

https://github.com/thomasloven/lovelace-card-mod

**Comment by keesschollaart81** [comment]
As discussed on Discord, I've added the `style` property to all card types. I consider this an exception as this property is only available to users who have this mod installed. Therefor I've added this remark in the tooltip description of this property. I hope you're happy with this? 

![image](https://user-images.githubusercontent.com/6755359/68084119-a7962b80-fe31-11e9-99a7-f1664beda5e7.png)

**Comment by ekendra-nz** [comment]
Thank you.

Now I'm seeing error message: 

"Unexpected error updating the schema's, message: Error: ENOENT: no such file or directory, open '/home/path/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.3.1/out/language-service/src/schemas/json/homeassistant.json'
