### ISSUE TITLE
YAMLSemanticError Mapping !secret A to !secret B

### ISSUE THREAD

**Issue by F0123X** [keesschollaart81/vscode-home-assistant#134]
Error notification: 

> File 'configuration.yaml' could not be parsed, it was referenced from path 'configuration.yaml'. This file will be ignored. Error(s): - YAMLSemanticError: Implicit map keys need to be followed by map values (Line: 40)

Relevant configuration.yaml section
```YAML
       trusted_users:
         !secret trusted_user_default_ip: !secret trusted_user_default_id
         !secret trusted_user_kiosk_ip: !secret trusted_user_kiosk_id
         !secret trusted_user_phone_ip: !secret trusted_user_phone_id
```

Screenshot of issue:
![github issue](https://user-images.githubusercontent.com/19984135/67965265-1d9f5600-fbd8-11e9-9401-af73bf1d10fa.png)

When I hover over the semicolon on line 40, I see the following errors:

> bad indentation of a mapping entry
> incomplete explicit mapping pair; a key node is missed
> bad indentation of a mapping entry
> incomplete explicit mapping pair; a key node is missed
> bad indentation of a mapping entry
> incomplete explicit mapping pair; a key node is missed
> bad indentation of a mapping entry
> incomplete explicit mapping pair; a key node is missed
 
When I hover over the trusted_user_default_ip, I see the following error:

> Incorrect type. Expected "object".

Note: This issue is similar to #117

**Comment by keesschollaart81** [comment]
It's indeed similar to 117 because it's an issue in the YAML Validator/Parser. That is easy to proof by switching the language in VS Code for this file to YAML (⌘K M or Ctrl+K M). Would you mind creating this as an issue in [that repository](https://github.com/eemeli/yaml) as a (non HA specific) validation error?

**Comment by keesschollaart81** [comment]
While I was investigating #159, I realised I was pointing to the wrong package as the origin of this error. It's actually this one: [YAML Parser](https://github.com/JPinkney/yaml-ast-parser/blob/master/src/loader.ts#L1278), please report it there!

I've updated the wiki to explain this:
https://github.com/keesschollaart81/vscode-home-assistant/wiki/Is-it-the-YAML-parser%3F

I'll close this issue as there is not much I can do.
