### ISSUE TITLE
Documentation or bug? (next steps after configuration)

### ISSUE THREAD

**Issue by erichiller** [keesschollaart81/vscode-home-assistant#135]
I'm not sure exactly what I'm supposed to do after configuring. I have it so yaml files are handled by this extension and the host and API long time password are configured. I can see in the Home Assistant log that the extension is connecting to my Home Assistant, but nothing changes within the the code editor.

I had thought that file management would take place via the API, but maybe I'm incorrect? Do I need to independently mount the files or setup a remote session of some kind?

If this is me just being a dumb user, maybe just a documentation update?

**Comment by keesschollaart81** [comment]
I guess this is documentation. I get this question from time to time. I'll write this documentation soon, in the meantime, I'll leave this issue open. To be continued... 

Short answer to your question, yes you need to independently mount the files locally. Remote session might be possible but I have not tested that myself.

**Comment by keesschollaart81** [comment]
Ok, I've updated the [Readme](https://github.com/keesschollaart81/vscode-home-assistant/blob/dev/README.md). Then I added some sections to the Wiki:
- [Configure your connection to HA](https://github.com/keesschollaart81/vscode-home-assistant/wiki/Configure-connection-to-HA)
- [Your config, local or remote?](https://github.com/keesschollaart81/vscode-home-assistant/wiki/Your-config,-local-or-remote%3F)
- [Troubleshooting](https://github.com/keesschollaart81/vscode-home-assistant/wiki/Troubleshooting)

I hope this makes it easier for new users to start with the right expectations. Let me know if I can still improve?!

**Comment by erichiller** [comment]
Thank you, I appreciate it!
