### ISSUE TITLE
"out" folder missing in installed extensions folder

### ISSUE THREAD

**Issue by naeramarth7** [keesschollaart81/vscode-home-assistant#1364]
Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [X] Other: [cdr/code-server](https://github.com/cdr/code-server)

I'm running VS Code on:
- [ ] Windows 
- [X] Mac 
- [X] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [x] Other: via [cdr/code-server](https://github.com/cdr/code-server)

In the latest version (1.20.0), the `out` folder is missing in the extensions folder after installation. I can see the following being logged:

```
[2021-07-06 22:05:35.413] [exthost] [info] ExtensionService#_doActivateExtension keesschollaart.vscode-home-assistant {"startup":true,"extensionId":{"value":"keesschollaart.vscode-home-assistant","_lower":"keesschollaart.vscode-home-assistant"},"activationEvent":"workspaceContains:**/configuration.yaml,**/ui-lovelace.yaml"}
[2021-07-06 22:05:35.413] [exthost] [info] ExtensionService#loadCommonJSModule file:///config/extensions/keesschollaart.vscode-home-assistant-1.20.0/out/extension
[2021-07-06 22:05:35.422] [exthost] [error] Activating extension keesschollaart.vscode-home-assistant failed due to an error:
[2021-07-06 22:05:35.422] [exthost] [error] Error: Cannot find module '/config/extensions/keesschollaart.vscode-home-assistant-1.20.0/out/extension'
```

Contents of `keesschollaart.vscode-home-assistant-1.20.0`:

```
abc@b00927cc9315:~/extensions$ ls -la keesschollaart.vscode-home-assistant-1.20.0/
total 60
drwxr-xr-x  7 abc abc 4096 Jul  6 22:04 .
drwxr-xr-x  8 abc abc 4096 Jul  6 22:04 ..
drwxr-xr-x  2 abc abc 4096 Jul  6 22:04 assets
drwxr-xr-x  4 abc abc 4096 Jul  6 22:04 .github
drwxr-xr-x  3 abc abc 4096 Jul  6 22:04 .husky
drwxr-xr-x 46 abc abc 4096 Jul  6 22:04 node_modules
-rw-r--r--  1 abc abc    5 Jul  6 22:04 .nvmrc
-rw-r--r--  1 abc abc 9817 Jul  6 22:04 package.json
-rw-r--r--  1 abc abc   95 Jul  6 22:04 .prettierignore
-rw-r--r--  1 abc abc 4955 Jul  6 22:04 README.md
-rw-r--r--  1 abc abc 2456 Jul  6 22:04 .vsixmanifest
drwxr-xr-x  2 abc abc 4096 Jul  6 22:04 yaml-language
```

Unzipping the cached vsix (`/config/data/CachedExtensionVSIXs/keesschollaart.vscode-home-assistant-1.20.0`) **the `out` folder is missing as well**.

**Comment by Klench** [comment]
I am experiencing the same issue but I am running vscode (and HA) in a docker container on Linux. It has worked flawlessly up until recently.

**Comment by Inervo** [comment]
Same issue as well. I've tried to install v1.20.0, 1.19.0, 1.21.0, still the same issue, no "out" folder.

Does anyone could maybe copy here this folder so that we can use this add-on :)

**Comment by naeramarth7** [comment]
Since this issue still persists for me (maxOS and using code-server), I'm using a workaround i.e. manually installing the extension:

1. Download and un-gzip:

```sh
curl https://marketplace.visualstudio.com/_apis/public/gallery/publishers/keesschollaart/vsextensions/vscode-home-assistant/1.21.0/vspackage -o keesschollaart.vscode-home-assistant-1.21.0.vsix.gz
gunzip keesschollaart.vscode-home-assistant-1.21.0.vsix.gz
```

2. In VSCode Hit `Ctrl` / `Cmd` + `P` and run the `Extensions: Install from VSIX...` command
3. Select the .vsix file

**Comment by pheetr** [comment]
I've run into this as well earlier today.
Code-server flavor of choice is linuxserver/docker-code-server. I've attempted the install on two systems running two different OS's with recent Docker versions, just in case. The result was the same issue.

Weirdly, the marketplace search within code-server provides v1.21 (screenshot below with lacking details and "invalid date" entries), even though 1.22 should be available, based on the [marketplace page](https://marketplace.visualstudio.com/items?itemName=keesschollaart.vscode-home-assistant&ssr=false#overview):
![image](https://user-images.githubusercontent.com/44616229/145119778-93e1b788-420c-47dd-a18f-55ac5dde349f.png)

Luckily, I've come across this post and @naeramarth7's workaround (thx! :) turned out to be working for me as well, so that's what I'm going with for now.
