### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by borpin** [keesschollaart81/vscode-home-assistant#139]
I am getting this error on v1.3.1

Unexpected error updating the schema's, message: Error: ENOENT: no such file or directory, open 'c:\Users\brian\.vscode\extensions\keesschollaart.vscode-home-assistant-1.3.1\out\language-service\src\schemas\json\homeassistant.json'

I get as far as here on the path
```
C:\Users\brian\.vscode\extensions\keesschollaart.vscode-home-assistant-1.3.1\out\language-service\src\schemas
```
where there is a `homeassistant.js` file but no `json` file or directory.

This is an update not a new install

**Comment by Diaoul** [comment]
I have this too on a brand new install.

**Comment by keesschollaart81** [comment]
Confirmed. Is a bug with the release from this afternoon (1.3.1), will fix this tomorrow!
