### ISSUE TITLE
Wrong Version number.

### ISSUE THREAD

**Issue by MickW69** [keesschollaart81/vscode-home-assistant#1466]
Log:
[Auth Phase] Connecting to Home Assistant... Tries left: 2
WebSocket Connection to Home Assistant closed with an error: Disconnected from Home Assistant with a WebSocket error with message: write EPROTO 12313928:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

[Auth Phase] Connecting to Home Assistant... Tries left: 1
WebSocket Connection to Home Assistant closed with an error: Disconnected from Home Assistant with a WebSocket error with message: write EPROTO 12313928:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

[Auth Phase] Connecting to Home Assistant... Tries left: 0
WebSocket Connection to Home Assistant closed with an error: Disconnected from Home Assistant with a WebSocket error with message: write EPROTO 12313928:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

Extension runs in: VS Code for Desktop  - Running on desktop, got the addon installed on Pi (don't use it because it occasionally crashes the Pi for some reason)

I'm running VS Code on: Windows 

I'm accessing my files: SMB Samba share

**Comment by brdweb** [comment]
I am experiencing the same exact issue, except I am accessing the files via SSHFS extension.
