### ISSUE TITLE
Can't see HA Files

### ISSUE THREAD

**Issue by sotatech** [keesschollaart81/vscode-home-assistant#15]
I'm new to VS Code but I think I've installed your extension OK with the URL and LLAT. However, I can't see any of the HA config files - do I need to setup an SSH connection to HA as well? Thanks!

**Comment by keesschollaart81** [comment]
It assumes that you have your configuration somewhere on your machines disk, locally.

For example, I  host my code on GitHub and use the hassio Git pull Add-on to get it to my HA server. I know others use a SSH FS connection to connect directly to the files on HA. In any case, today, the aim of extension is not solve that problem but to provide functionality around an existing, local, configuration.yaml.

**Comment by sotatech** [comment]
Ah, fine. Thanks for the clarification!
