### ISSUE TITLE
MQTT Sensor unknown attributes

### ISSUE THREAD

**Issue by realthk** [keesschollaart81/vscode-home-assistant#1516]
Because of the new Energy panel feature of 2021.8, I started to extend the configuration of my MQTT meter sensors with 
```
state_class
last_reset_topic
last_reset_value_template
```
[which is valid](https://www.home-assistant.io/integrations/sensor.mqtt/) and works fine, but currently not known by VSCode:
![vscode_mqtt_sensor](https://user-images.githubusercontent.com/5654575/129726277-71f08a74-80fc-4d8d-a0f2-2015266ef4e4.png)

**Comment by frenck** [comment]
Aah right. These are currently undergoing/pending change again, so I think we should hold off a potential fix until the API has stabilized.

**Comment by realthk** [comment]
Yeah, I see [the doc already mentions](https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes) `total` and `total_increasing` as possible `state_class` values, but my 2021.8.7 only accepts `measurement` yet.

**Comment by thehaxxa** [comment]
Additionally `number` is missing: 

`payload_available` 
`payload_unavailable`


![image](https://user-images.githubusercontent.com/2765052/131974003-8a2553ba-a581-4b60-b84c-47f707bd3f0a.png)
