### ISSUE TITLE
Documentation Update for VS Code Remote Dev SSH

### ISSUE THREAD

**Issue by eugeneniemand** [keesschollaart81/vscode-home-assistant#154]
The VS Code Remote development does work on Raspberry Pi. I think the important thing is how you connect. When connecting to the remote host you can choose the folder to open in the explorer. If I open /pi/home/ it does not seen to work, however if I open /pi/home/ha/homeassistant/ then it does. not sure if this is behaviour of the extension i.e. not sure how you determine where all the HASS code is

**Comment by keesschollaart81** [comment]
Thanks for the feedback. I've updated the readme to point to the wiki where I wrote some more guidance:
https://github.com/keesschollaart81/vscode-home-assistant/wiki/VS-Code-Remote-SSH
I hope this addresses your concerns.
