### ISSUE TITLE
TypeError: source_utils_1.default is not a function

### ISSUE THREAD

**Issue by mf-social** [keesschollaart81/vscode-home-assistant#155]
Several previous issues on this, all closed with a merged PR 'fixing' them.

This error appears constantly when trying to edit configuration.yaml

More here...

https://github.com/hassio-addons/addon-vscode/issues/58

**Comment by mf-social** [comment]
This ONLY occurs on configuration.yaml - all other yaml files are fine

Yamllint confirms no issues other than line length in any file, in fact configuration.yaml is not one that has any lint errors.

**Comment by keesschollaart81** [comment]
I need some YAML code / context to reproduce this:
- What OS?
- Only in VSCode Hassio Addon or also local?
- Can you share configuration.yaml

**Comment by mf-social** [comment]
Hassio on docker on a debian host.

Addon, can't say about local.

configuration.yaml is currently just 

```
homeassistant:
  whitelist_external_dirs:
    - camera
  packages: !include_dir_named packages 

config:

```

But it pretty much doesn't matter what's in there, every key press causes the error to pop up.
