### ISSUE TITLE
Properties tap_action, hold_action, double_tap_action are not allowed for entities card

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#160]
![Screenshot_20191117_190708](https://user-images.githubusercontent.com/37266727/69009330-aa366c00-096d-11ea-9d36-025ea2ed4c82.png)
![Screenshot_20191117_191050](https://user-images.githubusercontent.com/37266727/69009387-1c0eb580-096e-11ea-813f-41c3498eac43.png)

This properties are supported now: https://github.com/home-assistant/home-assistant-polymer/pull/4023

**Comment by keesschollaart81** [comment]
Correct, fixed with 2a289d755c753ed1a4ca1ba99e7899f363c25513.
Will ship with next release
