### ISSUE TITLE
Request textDocument/completion failed errors.

### ISSUE THREAD

**Issue by michalzadkowski** [keesschollaart81/vscode-home-assistant#166]
I am getting these errors over and over again:
```
[Error - 10:16:42 AM] Request textDocument/completion failed.
Message: Request textDocument/completion failed unexpectedly without providing any details.
Code: -32603
```

However I'm pretty sure my configuration (user settings, not workspace) is correct since I have these in the log:
```
Connecting to Home Assistant...
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
Connected to Home Assistant
```

I found a similar issue #108 , but it didn't help me much. Can anyone push me in the right direction? Am I missing something obvious?

**Comment by keesschollaart81** [comment]
Connection to HA and completion are two different things in the codebase.

Are you opening the files from your local machine or via remote SSH/Samba? Is it Windows/Mac?

**Comment by michalzadkowski** [comment]
Local machine, cloned repo of my HA. I’m on a Mac with Catalina

**Comment by deviant-studio** [comment]
i have this error too. i'm using samba on win10
