### ISSUE TITLE
Command not found when running from Code-Server

### ISSUE THREAD

**Issue by carlos-sarmiento** [keesschollaart81/vscode-home-assistant#1786]
I have a personal installation of Code-Server that I use for several things besides Home Assistant (this is the reason I don't use the add-on). This Code-Server instance is running straight in the "metal" (not using docker) and has access to my full environment (don't know if it is relevant, but it is running under my username with SystemD).

I installed the Home Assistant extension and configured it with my url and token. I know these work correctly because Node-Red is using the exact same credentials.

Nevertheless, whenever I try to run a command I get an error similar to this:

```
Command 'Home Assistant: Reload Template Entities' resulted in an error (command 'vscode-home-assistant.templateReload' not found)
```

I'm trying to find the logs for the extension, but haven't been able to figure out where to find them. Other extensions (not HA related) work fine. My Home Assistant installation itself works perfectly.

Please include the related YAML code:

```YAML
not applicable
```

Find my Home Assistant Configuration here:
[Link to Home Assistant Configuration](<link to repo here>)

Extension runs in:
- [ ] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [X] Other: Code-Server installed separately from any Hass Add-ons

I'm running VS Code on:
- [ ] Windows 
- [ ] Mac 
- [x] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:

**Comment by Alibader84** [comment]
Hello, Im have the same issue, can someone help please?
