### ISSUE TITLE
VSCode version incompatibility?

### ISSUE THREAD

**Issue by winstonojeda** [keesschollaart81/vscode-home-assistant#18]
Getting this error when installing:
`Unable to install because, the extension 'keesschollaart.vscode-home-assistant' compatible with current version '1.31.1' of VS Code is not found.`

**Comment by hairychris** [comment]
Update VS Code to work round this issue.

**Comment by winstonojeda** [comment]
> Update VS Code to work round this issue.

Worked!  Thank you!!!
