### ISSUE TITLE
Osx Installation

### ISSUE THREAD

**Issue by McVillano** [keesschollaart81/vscode-home-assistant#19]
I´ve installed the extension into VSCode on OSx, i've configured the https url and the long live token, i followed method 2, but now don´t see the home assistant config files in the explorer.

Do i need to do something to make this files visible?

**Comment by keesschollaart81** [comment]
How to deal with user vs workspace settings is documented [over here](https://code.visualstudio.com/docs/getstarted/settings). Let me know if this helps and if so, how I can update my docs to that this is more clear?!

**Comment by steveof2620** [comment]
> I´ve installed the extension into VSCode on OSx, i've configured the https url and the long live token, i followed method 2, but now don´t see the home assistant config files in the explorer.
> 
> Do i need to do something to make this files visible?

I don't seem to be able to install it on os x. Errors out in the extension manager. Is there anything I'm missing?
![screenshot_556](https://user-images.githubusercontent.com/46661819/55662796-b1878a00-5862-11e9-929b-ba77017986ed.jpg)

**Comment by dredzed** [comment]
Sorry for the complete newbie question, but I'm the same as McVillano above - I've tried to  follow installation method 2, but can't see any of my home assistant config files. I've generated and shared a Long-Lived Access Token , and entered url in both workspace and user settings. I assume the url is of the form : https://192.168.1.55:8123?
Thanks in advance for any help you can offer!

**Comment by Roeland54** [comment]
I have the same problem as @steveof2620 i can't install the extension even manually it doesn't work.

**Comment by keesschollaart81** [comment]
It should just work on OSx. Can you take a look at this issue and follow the steps provided to get the logs? Are you also running it as root?
