### ISSUE TITLE
seem not connected with windows, no auto-completion feature

### ISSUE THREAD

**Issue by rmaltais** [keesschollaart81/vscode-home-assistant#195]
for all my YAML files.

but with same parameters, work fine with my mac.

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X] Windows 
- [] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [X] Smb
- [ ] Other:

**Comment by keesschollaart81** [comment]
What does the log say? Got to view>output and select 'Home Assistant Language Service'
