### ISSUE TITLE
Remote_SSH to Pi Error

### ISSUE THREAD

**Issue by Dinges28** [keesschollaart81/vscode-home-assistant#197]
Hi Kees

As we spoke at the HomeAssistant state of the union;
I would like to issue a problem

Connecting to a Raspberry Pi with remote SSH give no errors, but saving a file gives an acces denied.
It needs to SUDO the command to have write access to the file.
A different user ssh connector had the same problem (i find that connector my cup of tea), but if there is placed an extra parameter in the connection configuration he puts a sudo in front of the commands. Maybe a solution? (https://github.com/SchoofsKelvin/vscode-sshfs/issues/104#issuecomment-467150071)

**Comment by keesschollaart81** [comment]
As documented here: 
https://github.com/keesschollaart81/vscode-home-assistant/wiki/VS-Code-Remote-SSH
This is not supported for Raspberry Pi's and has to do with the VS Code Remote SSH extension / ARM platform support...
