### ISSUE TITLE
Please allow to disable lack of configuration warning

### ISSUE THREAD

**Issue by qqgg231** [keesschollaart81/vscode-home-assistant#198]
Please allow me to disable this warning, which I get every vscode restart:
"Please configure Home Assistant (search for 'Home Assistant' in settings)."

I am using my own method to update config: I have config repo on github, and I have git-hook to git-pull on hassio and auto-restart when I commit new changes.

Btw my post-commit hook:

```
#!/usr/bin/env bash

branch_name=`git symbolic-ref --short HEAD`
retcode=$?

# Only push if branch_name was found (my be empty if in detached head state)
if [ $retcode = 0 ] ; then
    #Only push if branch_name is master
    if [[ $branch_name = "master" ]] ; then
        echo
        echo "**** Pushing current branch $branch_name to origin ****"
        echo
        git push origin $branch_name;
		curl -X POST -H "Authorization: Bearer HOME_ASSISTANT_API_KEY" -H "Content-Type: application/json" http://192.168.1.110:8123/api/services/script/git_pull
    fi
fi
```

**Comment by qqgg231** [comment]
please don't close

**Comment by qqgg231** [comment]
please don't close, the issue is not fixed

**Comment by qqgg231** [comment]
please don't close, the issue is not fixed

**Comment by frenck** [comment]
This configuration provides the autocomplete and enriches the schema validation.

It has nothing to do with the fact you are using custom deployment methods. Those can be uses side-by-side.

As the goal of this project/extension is to provide a language server to a running instance, I really don't get the motivation behind this request.

**Comment by qqgg231** [comment]
@frenck, ok I just see this warning every time I edit config. 

I wonder if it would be possible to disable it.

![2020-07-26 19_04_00-](https://user-images.githubusercontent.com/11590960/88484987-0a58c580-cf73-11ea-831e-293188cb4790.png)

**Comment by qqgg231** [comment]
It seems it require Home Asisstant instance config.
If I set language server config, it is still showing me this pop-up.


![2020-07-26 19_20_50-settings json - ha config git - Visual Studio Code](https://user-images.githubusercontent.com/11590960/88485298-23627600-cf75-11ea-903d-dca96f766d6c.png)


![2020-07-26 19_20_23-Settings - ha config git - Visual Studio Code](https://user-images.githubusercontent.com/11590960/88485294-147bc380-cf75-11ea-81d2-8e3eec253f96.png)

**Comment by frenck** [comment]
Yes, that is correct. It needs that, the extension is pretty much useless without it.

**Comment by qqgg231** [comment]
It is not useless, it has some home-assistant specific hints.

**Comment by frenck** [comment]
Those are really really limited without it. I honestly think you'd better use the RedHat YAML extension in such cases

**Comment by qqgg231** [comment]
RedHat YAML works only for .yml, not for .yaml 😢.
So not as good as this extension.

**Comment by frenck** [comment]
You can register the file extension `*.yaml` to be accepted by RedHat's YAML extension. As a matter of fact, this extension uses the libraries of RedHat's extension.

**Comment by qqgg231** [comment]
Ok, thank you.  I finally found this setting 😄 

https://stackoverflow.com/a/30776845/8896457
