### ISSUE TITLE
Extension keeping old settings

### ISSUE THREAD

**Issue by fillwe** [keesschollaart81/vscode-home-assistant#2]
Hey! So the first time i ran the extension i accidentally typed in the wrong adress. I updated it in settings.json and restarted visual studio code but i still got an error. Strangley enough in the error message it listed the old url. So i removed every setting in settings.json under the extension and uninstalled the extension. Restarted visual and installed the extension again, but even without filling in any settings it still pops up the same connection error message with the old url?

**Comment by fillwe** [comment]
Tried on an other computer, there I typed it in right the first time and there it is working great :-/

**Comment by keesschollaart81** [comment]
Ok, I see where the confusion comes from. I've updated the configuration section of the readme. Hopefully this is more clear now.
