### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by jchasey** [keesschollaart81/vscode-home-assistant#20]
I have installed the addon and it is working great. However I have two HA servers running and the entity completion only works for a single server. Is it possible to make the settings for the add-on specific to a folder i.e. 'Folder settings' and then I could switch between the servers.

**Comment by keesschollaart81** [comment]
Oh yes! Indeed, by default the HA settings are on user-level (so cross workspace/project). You can also set your settings on workspace level as documented [here](https://code.visualstudio.com/docs/getstarted/settings)
