### ISSUE TITLE
Deprecated folder mapping

### ISSUE THREAD

**Issue by damusmf** [keesschollaart81/vscode-home-assistant#2019]
When launching VSCode with this extension i am now getting depuration warning.  I have uninstalled and reinstalled the extension, downgraded to 1.26, upgraded back to 1.27.  Redid the long lived access token for HomeAssistant.  Completely deleted the folder this extension installs to and reinstalled.  Cannot seem to get rid of this error.  Causes auto complete to not function at all. 

VSCode Version: 1.66.0
OS: Win11
Extension Version: 1.27

```
(node:13184) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./dist/" in the "exports" field module resolution of the package at c:\Users\username\.vscode\extensions\keesschollaart.vscode-home-assistant-1.27.0\node_modules\home-assistant-js-websocket\package.json.
Update this package.json to use a subpath pattern like "./dist/*".
(Use `Code --trace-deprecation ...` to show where the warning was created)
```

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [x] Smb
- [ ] Other:

**Comment by kellyatkinson** [comment]
I have this error as well.  I have had it for several days. Thanks for reporting this.

**Comment by yangtfu** [comment]
Same

**Comment by nickh66** [comment]
Don't know if it's a fix or not but i stopped the error by editing the package.json file referenced in the error.
Original entry under Exports "./dist/": "./dist/" becomes "./dist/*": "./dist/*" & the error went away so far.

**Comment by holdestmade** [comment]
I aslo have this problem, what is the difference here ?
Thanks

`"./dist/": "./dist/" becomes "./dist/": "./dist/"`

**Comment by damusmf** [comment]
> Don't know if it's a fix or not but i stopped the error by editing the package.json file referenced in the error. Original entry under Exports "./dist/": "./dist/" becomes "./dist/_": "./dist/_" & the error went away so far.

I do not see the difference?

**Comment by flabbamann** [comment]
The difference is there are asterisks and markdown uses them for formatting. If you look closely there are parts in italic 😉. The line should look like `"./dist/*": "./dist/*"` to make the warning go away. I can't say if this is a proper fix or not 😉 

See this issue: https://github.com/home-assistant/home-assistant-js-websocket/issues/204

**Comment by damusmf** [comment]
> The difference is there are asterisks and markdown uses them for formatting. If you look closely there are parts in italic 😉. The line should look like `"./dist/*": "./dist/*"` to make the warning go away. I can't say if this is a proper fix or not 😉
> 
> See this issue: [home-assistant/home-assistant-js-websocket#204](https://github.com/home-assistant/home-assistant-js-websocket/issues/204)

Got it.  Seems to have done the trick! I also needed to apply the workaround from #1995 but now all seems to be good.  thank you.

Exports in packages.json
```
"exports": {
    ".": {
      "import": "./dist/index.js",
      "require": "./dist/haws.cjs",
      "default": "./dist/haws.umd.js"
    },
    "./haws.cjs": "./dist/haws.cjs",
    "./haws.umd.js": "./dist/haws.umd.js",
    "./dist/*": "./dist/*"
  },
  ```

**Comment by fgonza2** [comment]
I had the same issue, I replaced that line and the error went away, but auto-complete still not working.   what else should I look for?

**Comment by Nicholaiii** [comment]
> I had the same issue, I replaced that line and the error went away, but auto-complete still not working. what else should I look for? authentication with the server is OK and no errors anywhere, but as I type I see no autocomplete, say for the sensor names

@fgonza2 update to latest versions.

**Comment by alexdelprete** [comment]
> @fgonza2 update to latest versions.

I updated to latest version (v1.29), but autocomplete is still not working for me.
