### ISSUE TITLE
"Missing property "send_if_off" MQTT Climate" - this option is currently deprecated

### ISSUE THREAD

**Issue by WildRat** [keesschollaart81/vscode-home-assistant#2077]
"send_if_off" option is currently deprecated (https://www.home-assistant.io/integrations/climate.mqtt/#send_if_off), but still generates error message.

https://github.com/keesschollaart81/vscode-home-assistant/blob/4c336c7f70999201e7e7d2b22c4923cc348592f6/src/language-service/src/schemas/integrations/core/mqtt.ts#L1051

**Comment by TNTLarsn** [comment]
Already merged: https://github.com/keesschollaart81/vscode-home-assistant/pull/2331

**Comment by frenck** [comment]
Closing, as it has been adjusted in the above-mentioned PR.
