### ISSUE TITLE
Synchronize YAML formatting with Home Assistant

### ISSUE THREAD

**Issue by agners** [keesschollaart81/vscode-home-assistant#2082]
When running a mixed environment, where `automations.yaml` is edited through the UI and Visual Studio Code sometimes, lots of changes are introduced to the `automations.yaml` when VSCode add-on re-formats the file.

In particular quotes are changed from single quotes to double quotes, e.g.

```yaml
  description: ''
```

to

```yaml
  description: ""
```

New blocks are indented by two spaces:

```yaml
  trigger:
  - platform: device
```
to
```yaml
  trigger:
    - platform: device
```

While the YAML stays the same semantically, it introduces unnecessary changes which is annoying to review when using version control (e.g. git).

It does seem that the first issue can be resolved through the `redhat.vscode-yaml` add-ons `yaml.format.singleQuote` setting. However, it seems not to apply.

Using the Studio Code Server add-on 5.0.2. Parts of this has been reported in #114.

**Comment by frenck** [comment]
> lots of changes are introduced to the automations.yaml when VSCode add-on re-formats the file.

This is not done by this integration. The VSCode add-on comes bundled with Prettier which formats YAML.

**Comment by agners** [comment]
Yeah, but which one is used, and probably also settings used for the formatted can be influenced by this add-on, can't it? Seems Kees did agree [in this comment](https://github.com/keesschollaart81/vscode-home-assistant/issues/114#issuecomment-546581439).

**Comment by agners** [comment]
Ah I see what you are saying, its not that this VSCode extension uses prettier to format, but the VSCode Add-on comes with Pretty, which formats. Ok, that make sense. Will look into configure Prettier/deactivate that then.
