### ISSUE TITLE
The shorthand notation for logical conditions shows an error

### ISSUE THREAD

**Issue by Plazmin** [keesschollaart81/vscode-home-assistant#2093]
![5](https://user-images.githubusercontent.com/62091912/168379763-dde4f6c4-6d2f-4a17-a16f-f7907edb592a.png)

**Comment by frenck** [comment]
I'm not able to reproduce this issue from the given snippet. For example:

![CleanShot 2022-05-16 at 23 19 28](https://user-images.githubusercontent.com/195327/168684323-8c8ef52e-e9b8-4c09-9e7b-8255e67c3fb5.png)

Passes as part of an automation. Could you provide me a YAML snippet that I can copy and paste into my editor, which should not work?

**Comment by Plazmin** [comment]
Here is my automation where VSC reports an error.

```
- id: "disable_motion_sensor_new"
  alias: "Disable Motion Sensor New"
  initial_state: true
  trace:
    stored_traces: 15
  trigger:
    - platform: state
      entity_id:
        - person.adak
        - person.redi
        - person.kata
      from:
        - "ROD"
        - "w strefie ROD"
        - "w strefie* ROD"
        - "not_home"
      to:
        - "ROD"
        - "w strefie ROD"
        - "w strefie* ROD"
        - "not_home"
  variables:
    presence: "{{ expand('group.family')|selectattr('state','search','ROD')|list|count }}" 
    event: >
      {% if trigger.from_state.state == 'not_home' and 'ROD' in trigger.to_state.state %}
        {{ 'enter' }}
      {% elif trigger.to_state.state == 'not_home' and 'ROD' in trigger.from_state.state %}
        {{ 'leave' }}
      {% else %}
        {{ 'undetermined' }}
      {% endif %}
  condition:
    or:
      - and:
          - "{{ event == 'enter' }}"
          - "{{ presence == 1 }}"
      - and:
          - "{{ event == 'leave' }}"
          - "{{ presence == 0 }}"
  action:
    - service: homematic.set_device_value
      data:
        address: 00115BE967A7AB
        param: MOTION_DETECTION_ACTIVE
        interface: ip_ccu3
        value: "{{False if event == 'enter' else True}}"
        channel: 1
        value_type: boolean
```

![3](https://user-images.githubusercontent.com/62091912/168739462-cc142fd8-f4ee-4c77-8b18-4b0ae159e66b.png)

**Comment by frenck** [comment]
I copy and pasted your automation, but is shows up as valid on my end:

![CleanShot 2022-05-17 at 08 38 05](https://user-images.githubusercontent.com/195327/168745310-22a72b16-be32-4fdb-af37-2b81652ab0f0.png)

Which version of the extension (or add-on) are you using?

**Comment by Plazmin** [comment]
Hmm ... where's the problem? I think I have everything updated.

![4](https://user-images.githubusercontent.com/62091912/168751984-9d4439a0-5789-4ed1-8b75-a957121671e8.png)

**Comment by frenck** [comment]
Version 3.7.0 😧  That is a very old version (Nov 12, 2021) the add-on is currently on v5.0.3 (released yesterday).

See: <https://github.com/hassio-addons/addon-vscode/releases>

Make sure you have the community add-ons repository installed (you can do so using the following button):

[![Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fhassio-addons%2Frepository)

Next, check for updates.

**Comment by Plazmin** [comment]
The update fixed the problem. I don't know why I didn't have the community add-ons repository installed. Thank you for your help.

I have one more problem that I cannot solve.
There is no "paste" item in the right click menu. I have to use Ctrl-v. Do you know what could be the reason?
Of course, this happens with every yaml file.

![5](https://user-images.githubusercontent.com/62091912/168780423-225cb299-5056-45f3-b446-4c3018581ba9.png)

**Comment by frenck** [comment]
> There is no "paste" item in the right click menu. I have to use Ctrl-v. Do you know what could be the reason?

I have no idea, that might be an issue in code-server (https://github.com/coder/code-server/). It is not in control of the add-on or this extension.

Nevertheless, glad you original issue has been revolved 👍
