### ISSUE TITLE
Delay reconnecting when Websocket connection to Home Assistant fails 

### ISSUE THREAD

**Issue by michaelarnauts** [keesschollaart81/vscode-home-assistant#216]
I got redirected from here: https://github.com/hassio-addons/addon-vscode/issues/73

# Problem/Motivation

When updating or restarting Home Assistant, it goes down, but vscode is trying to reconnect to Home Assistant. There seems to be no delay between the reconnection attempts. Causing high CPU load during Home Assistant downtime.

## Expected behavior

Sleep a second or so between reconnection attempts.

## Actual behavior

```
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_vscode
20-01-17 18:34:47 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_vscode
20-01-17 18:34:47 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
20-01-17 18:34:47 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_vscode
...
```
Actually:
```
# docker logs hassio_supervisor 2>&1 | grep "18:34:47" | grep "WebSocket access" | wc -l
122 
```
It's trying to connect 122 times per second.

## Steps to reproduce

1. Run the Visual Studio Code Hass.io addon (https://github.com/hassio-addons/addon-vscode/issues/73).
2. Update Home Assistant, or restart it or something

## Proposed changes

Add a `time.sleep(1)` between reconnection attempts.

Extension runs in:
- [ ] VS Code for Desktop 
- [X] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [ ] Mac 
- [x] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:

**Comment by michaelarnauts** [comment]
It looks like the code does a delay of 1 second, but that's not what I see in my logs.

https://github.com/keesschollaart81/vscode-home-assistant/blob/master/src/language-service/src/home-assistant/socket.ts#L75

**Comment by Zixim** [comment]
I have the same symptoms.
Restarting Home assistant takes about 25 seconds,
in that time syslog gets absolutely hammered with 10705 lines !!!

Please...some one ... ??

**Comment by keesschollaart81** [comment]
Would you mind trying this with a local install of this extension? Like install the 'VS Code Configuration Helper' extension in a VS Code Instance on your local machine? When I reboot my HA I cannot reproduce this behaviour so it might be specific to the Hassio Addon-on (which I cannot run on my own pi to quickly test). On my local machine there is indeed a 1 second retry mechanism that seems to work?

**Comment by Zixim** [comment]
I don't mind trying anything, it's just that I do not use VS Code anywhere - except as a web UI tool to do some quick config changes in Home Assistant.

If you give me detailed instructions, or if you want a remote session into a VM...

**Comment by keesschollaart81** [comment]
Thanks, it's as simple as installing VS Code on your machine, install [this extension](https://marketplace.visualstudio.com/items?itemName=keesschollaart.vscode-home-assistant), get your configuration to your machine and open that folder.

**Comment by Zixim** [comment]
> get your configuration to your machine and open that folder.

So, I copied `configuration.yaml` from the HA instance to a folder on the machine that is running VSCode.
Then, in VSCode, File>Open Folder and selected that folder

Now what ?

**Comment by BarrettLowe** [comment]
My restart takes much longer because of this. Sometimes it increases my reboot time to 3-4 minutes when it typically takes approximately 30 seconds. I'm running the addon in hassio. If it works standalone I'll switch to that. Let us know what you find

**Comment by Zixim** [comment]
guess we'll have to live with it, or remove VSCode, or at the very least isable the auto startup for VSCode.

**Comment by Zixim** [comment]
wonderful.

**Comment by frenck** [comment]
This definitely needs to be added. I'll take a look.

**Comment by michaelarnauts** [comment]
@frenck did you had the time to look at this?
