### ISSUE TITLE
Is it possible to check HA configuration from VSCode?

### ISSUE THREAD

**Issue by rschuiling** [keesschollaart81/vscode-home-assistant#22]
Thanks for the great extension! I would love if I could check my Home Assistant configuration right from VSCode. Would it be possible to provide something for that?

**Comment by keesschollaart81** [comment]
That's a great idea and definitely possible, I've added it to the list! I'll report back in this issue when this is added.

**Comment by rccoleman** [comment]
I’ve added custom tasks in VS Code to check config and to runtime reload as many domains as are available (automations, scripts, groups, core, themes), but it would be great if these were just available ‘out of the box’. I’m using hass-cli via a command line task to kick them off.

**Comment by rschuiling** [comment]
Could you perhaps integrate this?:

https://community.home-assistant.io/t/community-hass-io-add-on-visual-studio-code/107863/166?u=emphyrio
