### ISSUE TITLE
Request textDocument/completion failed unexpectedly without providing any details.   Code: -32603

### ISSUE THREAD

**Issue by See182** [keesschollaart81/vscode-home-assistant#2247]
Currently I can only use the addon sucessfully through the VS Code Addon on Home Assistant and with a copy of the configuration saved local on my laptop. Everything else SMB, SSH and VS Code Remote always results in following error, while trying to use the entity autocomplete function:

```VS Code Output
[Home Assistant Language Server(21304)] Started and initialize received
Applying schemas to 41 of your configuration files...
Assigning z:/configuration.yaml the configuration.yaml schema
Assigning z:/automations.yaml the configuration.yaml/automation schema
Assigning z:/automations.yaml the configuration.yaml/automation schema
Assigning z:/scenes.yaml the configuration.yaml/scene schema
Assigning z:/scripts.yaml the configuration.yaml/script schema
Assigning z:/configuration%5Cbinary_sensor.yaml the configuration.yaml/binary_sensor schema
Assigning z:/configuration%5Ccover.yaml the configuration.yaml/cover schema
Assigning z:/configuration%5Csensor.yaml the configuration.yaml/sensor schema
Assigning z:/configuration%5Cswitch.yaml the configuration.yaml/switch schema
Schemas updated!
[Error - 23:33:26] Request textDocument/completion failed.
  Message: Request textDocument/completion failed unexpectedly without providing any details.
  Code: -32603 
Discover all configuration files because file:///z%3A/configuration/light.yaml got updated and new files were found...
[Error - 23:34:06] Request textDocument/completion failed.
  Message: Request textDocument/completion failed unexpectedly without providing any details.
  Code: -32603 

```

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [X] Via remote SSH 
- [X] Smb
- [X] Other: VS Code Remote Addon (Home Assistant Edge Addon)

**Comment by See182** [comment]
It seems to work with the VS Code Remote Addon, if I map the Path to the root instead of the config folder. I haven't tried the other methods like SMB or SSH FS.

**Comment by ken-wolfe** [comment]
I have the exact same issue.

**Comment by kent7854** [comment]
I am having the same issue. I'm running VS Code on my Windows desktop and remote logging into the Ubuntu server where I'm running Home Assistant in a Docker Container. Not sure if that helps anyone trying to debug this but if I can supply any additional information let me know.

**Comment by frenck** [comment]
This issue occurs when the exention isn't able to connect to Home Assistant.

This can be either incorrect credentials or URLs in the extensions configuration, connections issues, or can be caused by an out-dated Home Assistant installation.

../Frenck
