### ISSUE TITLE
connect to HomeAssistant on rastbery pi 4

### ISSUE THREAD

**Issue by DukeNuken** [keesschollaart81/vscode-home-assistant#226]
Hello. I am not sure how to connect to HA which runs on raspberry pi 4 (hass.io)
When I install that extension to my windows Visual Studio Code it asking about Host Url which is default http://hassio.local:8123/ and long life token - which I don't understand where I should get.

 So questions here:
1) Can that extension work somehow for me? Because in some response I saw raspberry pi not supported in any case.
2) Which type of connection does it use? So my windows Visual Studio Code + that extension it is a client, but what should be installed on HomeAssitant to make it work?
3) I see the ways how it can be connected - from local disk, Via remote SSH,  Smb. Which of those can work for me?

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X ] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:

**Comment by DukeNuken** [comment]
Ok. I found what I can get  "long live token" in WebUI and when I start to edit the local copy of config files it shows some helpers, but like the manual said it is only local files and it doesn't update the server copy. For update on server I should use SAMBA addon for windows folder share, because Hassio Addon "Visual Studio Code" show message "This add-on is not available on your system." and  "VS Code Remote development" doesn't support raspberry pi - connection error show the link https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites and looks like my raspberry pi have Alpine Linux 3.11.2 which not supported. 

Looks like it is pure support for raspberry pi devices.

**Comment by alonjr** [comment]
hello @DukeNuken, did you manage to figure out how to setup your environment? I too have a similar setup and would like to be able to edit my YAML config files using Visual Studio Code. What is the Home Assistant Root URL? I get an error when placing the usual HA URL (I did figure out the Long Lived Access Token through the Profile page on HA webui).
thanks

**Comment by Nxt3** [comment]
I'm also facing the same issue. I have my settings like so and still get the following error:

```
Error connecting to your Home Assistant Server at http://homeassistant.local:8123 and token 'en9iQ...', check your network or update your VS Code Settings, make sure to (also) check your workspace settings! Error: ERR_CANNOT_CONNECT
```

<img width="841" alt="Screen Shot 2020-10-28 at 4 33 21 PM" src="https://user-images.githubusercontent.com/2940826/97493436-541ec680-193b-11eb-8cde-7fd8a3ac7ab6.png">
