### ISSUE TITLE
Allow for Config Formatter to be disabled

### ISSUE THREAD

**Issue by droans** [keesschollaart81/vscode-home-assistant#2303]
The configuration formatter can be extraordinarily slow, usually taking around 30s on my computer. It also will often use a different style than I use, even though my style is also syntactically correct. HA will also be unable to properly validate the YAML files until the check has completed, which can cause issues if it unexpectedly performs a check during a restart or YAML reload.

Allowing this to be disabled in settings would be a beneficial feature for most users.

System info:

* VSCode Docker Image: linuxserver/code-server:latest
* HA Docker Image: home-assistant/home-assistant:stable
* CPU: Ryzen 5600X
* RAM: 32GB
* SSD for HA and VSCode Docker data and containers

**Comment by frenck** [comment]
This extension does not provide a code formater.

../Frenck
