### ISSUE TITLE
Template explorere / renderor 

### ISSUE THREAD

**Issue by johntdyer** [keesschollaart81/vscode-home-assistant#2350]
Would be cool if there was a way to experement / iterate with templates like you are able to do in the developer tool, only within VSCode... Basically thinking something that behaves like a markdown parser where the template rendering is on the right side

**Comment by frenck** [comment]
Do this in a way the part you want to evaluate and render it as a template.

![CleanShot 2022-12-12 at 15 26 01](https://user-images.githubusercontent.com/195327/207070131-75f6842d-998a-478a-b040-323a6151765a.png)

I don't think it makes much sense to re-create the developer tools... just use the developer tools 😄
