### ISSUE TITLE
"Got xxxx entities from Home Assistant" looping forever

### ISSUE THREAD

**Issue by Motik68** [keesschollaart81/vscode-home-assistant#2478]
Whenever I trigger auto-completion, the output log gets flooded with the following message, many times per second.
```
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
Got 1533 entities from Home Assistant
```
This produces high CPU usage and does not stop until I exit VS Code. The same thing happens whether I connect through SMB or SSH.

Any idea?

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [X] Via remote SSH 
- [X] Smb
- [ ] Other:

**Comment by frenck** [comment]
> Whenever I trigger auto-completion, the output log gets flooded with the following message, many times per second.

That is expected, it listens for entity changes (which includes new entities). This is thus correct behavior.

> This produces high CPU usage and does not stop until I exit VS Code

I don't think this is related, but a red herring you are looking at.

../Frenck

**Comment by Motik68** [comment]
Thank you Frenck for the explanation (and for all the good work!)
