### ISSUE TITLE
Auto Completion doesn't work for me

### ISSUE THREAD

**Issue by bitwon** [keesschollaart81/vscode-home-assistant#254]
Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [X] From local disk over [SSH FS](https://github.com/SchoofsKelvin/vscode-sshfs)
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:  

I created the token and checked the log of the extension: 
`[Home Assistant Language Server(3588)] Started and initialize received
Schema's updated!
Connecting to Home Assistant...
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
Connected to Home Assistant
`

Seems to work correct, but I can't get auto completion to work. Hassio is running on a Raspberry 4B but don't know if this matters for that case...

![24-02-_2020_10-28-26](https://user-images.githubusercontent.com/60846394/75141565-8499cb00-56f1-11ea-8df3-73fae49d2241.gif)

**Comment by fbrinker** [comment]
Same for me with Linux and Windows 🤔 
Home Assistant 0.105.5

**Comment by bitwon** [comment]
@fbrinker The error occurs because with SSH FS we don't have a local file structure. I created a local .yaml file and the auto completion works perfect.

@keesschollaart81 Maybe it's possible to add support for that case in future?

**Comment by fbrinker** [comment]
Hmm but it worked in the past with SSH FS - interesting

**Comment by bitwon** [comment]
Strange. I didn't know this, because I installed it yesterday. 

@fbrinker Since when does it not work for you anymore?

**Comment by keesschollaart81** [comment]
Thanks for the GIF!

From what I can see it is because you dont have the configuration.yaml in the root of the workspace? Can you test to connect to the config folder so that configuration.yaml is in the root?

**Comment by bitwon** [comment]
Unfortunately the same behaviour as before.
![image](https://user-images.githubusercontent.com/60846394/76169279-d2451780-6176-11ea-99f4-5fb013d55604.png)
In the log I get the messages: "Got 172 entities from Home Assistant"
But only in the local files I get the message: "Discover all configuration files because file:///c%3A/Users/.../Visual%20Code/test.yaml got updated and new files were found...
Schema's updated!"

**Comment by bitwon** [comment]
Made the test with the Hass Samba Add-on and it works without problems...

**Comment by bitwon** [comment]
@keesschollaart81 Are there already news about this?

**Comment by sophof** [comment]
I seem to be having this exact issue and I don't see any resolution here?
