### ISSUE TITLE
Icon property in script.yaml throws warning in VSC in HA 106.2

### ISSUE THREAD

**Issue by holdestmade** [keesschollaart81/vscode-home-assistant#259]
When entering the new icon property in version 106.2 in a script, VSC shows a warning that the property is not allowed.

Steps to reproduce
Add:
`icon: mdi:bulb`
to a script

**Comment by SeanPM5** [comment]
@keesschollaart81 I just updated to 1.6.1 extension and it seems to have fixed these warnings for scenes (yay), but not scripts. 

![script](https://i.imgur.com/ixsmwxA.png)

Scripts can also have `icon:` too as of [0.106](https://www.home-assistant.io/blog/2020/02/26/release-106/#other-noteworthy-changes).

**Comment by holdestmade** [comment]
Strange, I didn't even mention scenes only scripts !
