### ISSUE TITLE
Can't get validation working

### ISSUE THREAD

**Issue by benjgos** [keesschollaart81/vscode-home-assistant#262]
I'm new to VSCode and the Home Assistant Config Helper, so I assume I've missed something.

The extension connects to Home Assistant and I have auto-completion of entities, but I don't have field validation as in the second gif on the main page.
I've tried verifying using the example in the gif, in configuration.yaml, when inserting elevation: "high", I don't get any warning on "high".
Also might be related (or might not be implemented), I don't seem to have any definitions when I right click on anything such as "elevation" in configuration.yaml, or "entities" in ui-lovelace.yaml, etc... 

I'm using VSCode on Mac, fetching files from my home assistant core (Docker) install via the VSCode SFTP extension.

**Comment by keesschollaart81** [comment]
Can you share with me the logs? [howto in Wiki](https://github.com/keesschollaart81/vscode-home-assistant/wiki/Troubleshooting)
