### ISSUE TITLE
Request textDocument/completion failed.

### ISSUE THREAD

**Issue by felipemathies** [keesschollaart81/vscode-home-assistant#2677]
After the connection when i try to edit any config file i get this error:

[Error - 1:02:39 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed unexpectedly without providing any details.
  Code: -32603 

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [X] Mac 
- [ ] Linux 

I'm accessing my files:
- [] From local disk 
- [X] Via remote SSH 
- [ ] Smb
- [ ] Other:

**Comment by frenck** [comment]
This means either of the following:
- Your connection details aren't correct
- There are connection issues
- Your version of Home Assistant is outdated; some calls may not succeed.

../Frenck
