### ISSUE TITLE
Env vars HASS_SERVER & HASS_TOKEN not used

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#27]
The support for HASS_TOKEN & HASS_SERVER environment variables (added in #11) no longer work in the latest version.

It seems that these were lost in translation during the migration/refactor towards the language server. This causes a problem for the Home Assistant Visual Studio Code add-on for Hass.io, since it relies on them.

The result is the add-on now spawns continues popups:

![image](https://user-images.githubusercontent.com/195327/57522971-ee441680-7323-11e9-857e-cc85ec01a7f1.png)

**Comment by keesschollaart81** [comment]
How could I have missed that!? Sorry! They're back now in v0.5.6 which I just released!
