### ISSUE TITLE
Studio Code Server Current version: 5.8.2 addon version fails most entity selectors

### ISSUE THREAD

**Issue by SirGoodenough** [keesschollaart81/vscode-home-assistant#2751]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

Versions of Studio Code Server Current version: 5.8.2 addon loaded today cause the YAML to highlight most if not all entity domains.  Blueprints still work, but the code is flagged as deprecated.

This is the Home Assistant blueprint being flagged:

![Screenshot_20230720_160217](https://github.com/keesschollaart81/vscode-home-assistant/assets/47349533/967de83f-3451-4c96-9953-d49f14244fb2)

**Comment by frenck** [comment]
That is not a bug, but correct.

../Frenck
