### ISSUE TITLE
Scanning irrelevant files

### ISSUE THREAD

**Issue by roflcoopter** [keesschollaart81/vscode-home-assistant#287]
Extension runs in:
- [ ] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [X] Other: Running coder in standalone docker

I'm running VS Code on:
- [ ] Windows 
- [ ] Mac 
- [X] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:  

As a follow-up on #48, i think adding an option to specify the root folder of the configuration would be good for performance, or for the extension to only scan the files which it is associated with, something like this
```
   "files.associations": {
      "/workspace/hass/**/*.yaml": "home-assistant",
    }
```
My workspace contains *a lot* of files and the extensions loops through all of them, which is not very efficient. 

I cant use the extension in this state since it puts heavy toll on my CPU, and its also really slow to fetch entities and apply schemas, which is a shame because the extension is super useful.
Sadly i dont know enough to provide a PR myself

**Comment by rirofal** [comment]
You can use the workspace-file to define files that you would like to exclude...

`{
	"settings": {
		"files.exclude": {
			"home-assistant_v2.db*": true,
			"pyozw.sqlite": true
		},
	}
}`

https://code.visualstudio.com/docs/getstarted/settings

**Comment by roflcoopter** [comment]
Yes but from my experience the extension does not respect that and still searches through every file

**Comment by roflcoopter** [comment]
This is still an issue for me

**Comment by frenck** [comment]
This has been fixed in the v1.8.0 of this extension.
Custom `files.associations` are now honored.

**Comment by roflcoopter** [comment]
Amazing! Can't thank you enough

**Comment by roflcoopter** [comment]
@frenck Just tested 1.8.1 out, and it seems a little better but for some reason its still scanning all the files in the workspace.
This is the output when i start up code-server

```log
[Home Assistant Language Server(802)] Started and initialize received
Cannot find the files in folder aind/var/lib/anbox/data
Connecting to Home Assistant...
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant... Tries left: 3
The include could not be resolved because no file(s) found in 'packages' included with 'include_dir_named' from 'dev-hass/configuration.yaml'
The include could not be resolved because no file(s) found in 'packages' included with 'include_dir_named' from 'dev-hass/configuration.yaml'
File '/workspace/hass/lovelace/views/01_homepage_view.yaml' could not be parsed, it was referenced from path 'lovelace.yaml/views'.This file will be ignored. Error(s): 
 - YAMLSemanticError: Indicator : missing in flow map entry
 - YAMLSyntaxError: Document contains trailing content not separated by a ... or --- line
File '/workspace/hass/lovelace/views/03_temp_view.yaml' could not be parsed, it was referenced from path 'lovelace.yaml/views'.This file will be ignored. Error(s): 
 - YAMLSemanticError: Indicator : missing in flow map entry
 - YAMLSyntaxError: Document contains trailing content not separated by a ... or --- line
File '/workspace/hass/lovelace/views/03a_garden_view.yaml' could not be parsed, it was referenced from path 'lovelace.yaml/views'.This file will be ignored. Error(s): 
 - YAMLSemanticError: Indicator : missing in flow map entry
 - YAMLSyntaxError: Document contains trailing content not separated by a ... or --- line
File '/workspace/hass/lovelace/views/05_system_view.yaml' could not be parsed, it was referenced from path 'lovelace.yaml/views'.This file will be ignored. Error(s): 
 - YAMLSemanticError: Indicator : missing in flow map entry
 - YAMLSyntaxError: Document contains trailing content not separated by a ... or --- line
Applying schema's to 68 of your configuration files...
Schema's updated!
```

As you can see it scans files in the folder named aind and dev-hass.
And as soon as i open a .yaml in the configuration one of the cores stay maxed out for a few minutes
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                               
1459842 root      20   0  941404 172776  30424 R 105,6  2,1   6:16.74 /usr/lib/code-server/lib/node /root/.vscode/extensions/keesschollaart.vscode-home-assistant-1.8.1/out/server/server.js
```

My file associations look like this
```json
   "files.associations": {
      "/workspace/hass/**/*.yaml": "home-assistant",
      "/workspace/hass/**/*.yaml.disabled": "home-assistant",
      "/workspace/hass/appdaemon/**/*.yaml": "yaml",
      "*.yaml": "yaml",
      "*.yaml.disabled": "yaml"
  }
```

**Comment by frenck** [comment]
That seems correct to be honest?

**Comment by roflcoopter** [comment]
Well, it shouldnt go into the folder ```aind``` or ```dev-hass```, as these are not in the ```hass``` folder and are not matched by the ```files.associations``` settin, right?

**Comment by roflcoopter** [comment]
I recently switched to using Visual Studio Codespaces instead of code-server, and i dont see this problem there. I also started using workspaces instead of opening a giant folder which seems to have helped. Thanks for your time!
