### ISSUE TITLE
1.6.1 breaks yaml auto indentation

### ISSUE THREAD

**Issue by VDRainer** [keesschollaart81/vscode-home-assistant#288]
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

Auto indentation in yaml files doesn't work anymore after installing 1.6.1.
Going back to 1.5.0 or disabling the extension brings indentation back.

```YAML
your:
   - yaml
```

and/or point to a repository containing your Home Assistant Configuration

**Comment by pszafer** [comment]
Have same issue.
I know workaroud for it.

Go to `settings.json`, paste:
```
"editor.autoIndent": "full"
```

and till closing of editor indentation should be working.

**Comment by wixoff** [comment]
Confirmed here too, and the workaround does help but only temporarily.

**Comment by VDRainer** [comment]
Still an issue in 1.6.5

**Comment by frenck** [comment]
Fixed in #374 

![2020-07-12 09 04 01](https://user-images.githubusercontent.com/195327/87240996-e3e94500-c41e-11ea-98cb-efd01f04ba95.gif)

**Comment by frenck** [comment]
Fixed in 1.7.0
