### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by kloggy** [keesschollaart81/vscode-home-assistant#29]
Unless I am doing something wrong the auto-complete does not seem to support packages.
If I *am* wrong can you tell me what I might be doing and if I am right can you say if this is ever likely to be a possibility?

This is a great extension even with the (apparently) limited functionality with packages, so thanks for creating it!

**Comment by keesschollaart81** [comment]
Your HA repo is not everything, right? Can you maybe share some of the relevant config? Like the homeassistant section in the configuration.yaml / 1 package / outline of the folder structure?

Packages should work. I've tested it with [this repo](https://github.com/frenck/home-assistant-config/) which uses packages extensively...

**Comment by kloggy** [comment]
No my HA repo is just a small part of my config just as a place to make it available to others who asked for the garden irrigation package.

I have moved almost everything out of ```configuration.yaml``` but possibly you are interested in this line?
```
packages: !include_dir_named packages/
```

My folder structure looks like this:
![image](https://user-images.githubusercontent.com/38220016/57657681-fde98680-75d3-11e9-8127-fe51fab8e033.png)

With this as an example of a package folder
![image](https://user-images.githubusercontent.com/38220016/57657728-22ddf980-75d4-11e9-8425-7d273fcffa78.png)

The thing I have found is that, for example, the entity autocomplete will only find entities in the file currently being edited.

Let me know if there is anything else you'd like me to provide and I will gladly do so.

PS While I've got you here, recently my ```.yaml``` file icons seem to have changed to be the same as generic text files. Is that anything to do with this extension?

![image](https://user-images.githubusercontent.com/38220016/57657876-adbef400-75d4-11e9-969a-ae749dc874ad.png)

**Comment by keesschollaart81** [comment]
- Be sure that if you open your repo, the configuration.yaml is in the root of the workspace. So in case of [this repo](https://github.com/frenck/home-assistant-config/), open de 'config' folder with VS Code
- Make sure that in the bottom right corner of VS Code the language is set to 'Home Assistant' (item 2 in the readme.md)
- Please take a look at the 'output' (view>output) and set the combo to 'Home Assistant Language Server', there might be an error there
- File icons are by language (not perse by extension) and there are no icons yet for Home Assistant but that will change [soon](https://github.com/vscode-icons/vscode-icons/pulls)

**Comment by kloggy** [comment]
Thanks for the pointers:

- ```configuration.yaml``` is in the root of my folder (as is ```ui-loveleace.yaml```)
- Language is set to 'Home Assistant'
![image](https://user-images.githubusercontent.com/38220016/57680680-12566f00-7626-11e9-9585-827b7983da30.png)
- No errors in the Output
![image](https://user-images.githubusercontent.com/38220016/57680814-5fd2dc00-7626-11e9-8218-ec4a5a201980.png)
- File icons in the next version - great news AND I looked at the issue on GitHub and saw the comment about the YAML extension interfering with the HA one. I have disabled the YAML extension and yes, many things are better now (most specifically I had some strange highlighting going on). It might be worth mentioning that in the docs?

However I still only get autocomplete entities that appear within the current file as shown here. My config has many more ```binary_sensors``` than offered in the list which only shows those that appear in the current file being edited.

![image](https://user-images.githubusercontent.com/38220016/57681126-00c19700-7627-11e9-9fc8-d5b32c7fc00e.png)

**Comment by keesschollaart81** [comment]
That last screenshot completes with the 'tokens' in the file which is disabled in the Home Assistant Language. Are you sure that that file is also set to 'Home Assistant'? Does completion work in the `configuration.yaml`? And if not, when trying completion in the `configuruation.yaml`, do you see 'Got *** entities from Home Assistant' message in the output?

**Comment by kloggy** [comment]
_Are you sure that that file is also set to 'Home Assistant'?_ - Yes...

![image](https://user-images.githubusercontent.com/38220016/57683102-f2757a00-762a-11e9-9500-ed0c62bd7153.png)

_Does completion work in the configuration.yaml?_ - Yes it does!

**Comment by keesschollaart81** [comment]
Hmm, very likely because of the spaces in the folder/files names. Fixed with: 4cecc6e1b49107dfd89ad003264ef89f13fc8dea

**Comment by keesschollaart81** [comment]
Can you confirm that it does work in folders/files without spaces/special characters?

**Comment by kloggy** [comment]
Yes it does seem to. Thank you!

**Comment by kloggy** [comment]
Hi, 
Did file icons make it into v0.6.0?
Obviously I'm asking because I don't see them, so if they didn't, no problem, I'll wait!

**Comment by keesschollaart81** [comment]
Track it here: https://github.com/vscode-icons/vscode-icons/pull/2054
