### ISSUE TITLE
YAML node anchors

### ISSUE THREAD

**Issue by deluxestyle** [keesschollaart81/vscode-home-assistant#30]
I'm using in my lovelace file a few YAML node anchors.
Unfortunately it show as an error within Visual Studio

![image](https://user-images.githubusercontent.com/662779/57581671-01d5b580-74bb-11e9-9f61-fd597bcdaf8d.png)

**Comment by keesschollaart81** [comment]
Cool, YAML-anchors were new to me but looking at your configuration, it's totally awesome, ! I've just updated the schema to allow for additional properties.

The only error now -in your repo- is about the `popup_cards`. I'll think about how to deal with that later today/this week. To be continued!

**Comment by deluxestyle** [comment]
thank you very much. will try out as soon as possible. great work so far. helps a lot to maintain my current home assistant installation. 
thank you so much
