### ISSUE TITLE
Schema's not being loaded

### ISSUE THREAD

**Issue by sammyke007** [keesschollaart81/vscode-home-assistant#3017]
Hi
I'm running Home Assistant Config Helper as an extension in Code Server (running in an LXC).
I can connect to Home Assistant and entity completion is working fine, but I can't get the other options to work. The schema's wont load.

Home Assistant Language Server outputs:
[Home Assistant Language Server(12402)] Started and initialize received
Cannot find the files in folder dev/fd

Do I need to mount something?

Extension runs in:
- [ ] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [X] Code Server: 

I'm running VS Code on:
- [ ] Windows 
- [ ] Mac 
- [X] Linux 

I'm accessing my files:
- [ ] From local disk 
- [X] Via remote SSH 
- [ ] Smb
- [ ] Other:

**Comment by frenck** [comment]
Confirmed, see the issue too.

Not sure what caused it. Running a git bisect now to find the commit that caused it.

../Frenck

**Comment by frenck** [comment]
![CleanShot 2024-01-12 at 13 09 50@2x](https://github.com/keesschollaart81/vscode-home-assistant/assets/195327/b310c4ba-67a0-4076-935f-412384303b34)

Next up: Figuring out why this PR messes up the schemas

**Comment by sammyke007** [comment]
I've switched to the "official" Vscode on Windows and using Remote SSH to HA OS it does work 100%. Schemas are working and so does entity completion. Strange...

**Comment by hellcry37** [comment]
> I've switched to the "official" Vscode on Windows and using Remote SSH to HA OS it does work 100%. Schemas are working and so does entity completion. Strange...

Dunno on what you switched, but is not working for sure. I am using "official" Vscode on Windows and Remote SSH but on a docker container and is definitively a issue.

**Comment by alexbNz2021** [comment]
if you go back to 1.39 it works, on macos and linux looks like a werid update as the URLs are different between the versions for the Schema

**Comment by Bartsz** [comment]
I have similar issue, I get autocompletion on entities and services, but schema doesn't work.
I'm using vs code server on HA running in VirtualBox.

Unlike sammykey007, I can open folder **dev/fd** using VS Code and list the files inside but i can't open the files inside using VS Code

Can I provide any more info to help finding root couse?
