### ISSUE TITLE
Property X is not allowed error using the collapsable input feature in Blueprints

### ISSUE THREAD

**Issue by SirGoodenough** [keesschollaart81/vscode-home-assistant#3203]
Using current version of the Code Server Add-on 
```texr
Studio Code Server
Current version: 5.16.3 (Changelog)
```
When utilizing the collapsible input feature of blueprints, several of the lines are listed as Property X is not allowed.
https://www.home-assistant.io/docs/blueprint/schema/#blueprint-input-sections

![image](https://github.com/user-attachments/assets/7f0e93d7-e920-49c7-93a0-ddc0a4c8f98d)

I use this in nearly all my blueprints. samples for test can be found in these locations:
https://github.com/SirGoodenough/HA_Blueprints/tree/master/Automations
https://github.com/SirGoodenough/HA_Blueprints/tree/master/Scripts

**Comment by frenck** [comment]
![CleanShot 2024-10-05 at 10 22 12@2x](https://github.com/user-attachments/assets/ea141471-1537-4db2-8e76-1ae9cab2e2b6)

Fixed will make a pull request.
