### ISSUE TITLE
Linting for deprecated node names

### ISSUE THREAD

**Issue by rcdailey** [keesschollaart81/vscode-home-assistant#3219]
Recent HASS releases have renamed some nodes. For example `trigger` is now `triggers` in automations. And services are now actions. Would it be possible to get linting (in the form of yellow squigglies) for node names that are deprecated? Deprecated is probably the wrong word to use here since the HASS release notes explicitly state that the old names are not deprecated; however for the purposes of this extension, I'd like to treat them as such so I can at least easily see when names can be updated as I edit/update my YAML files.

**Comment by frenck** [comment]
The extension has been update to support whatever is possible at this point for this extension.
Meaning, in most cases it will report you are using a legacy syntax.

../Frenck
