### ISSUE TITLE
Missmatched documentation URL for `unit_of_measurement`

### ISSUE THREAD

**Issue by RSickenberg** [keesschollaart81/vscode-home-assistant#3320]
https://github.com/keesschollaart81/vscode-home-assistant/blob/dev/src/language-service/src/schemas/integrations/core/homeassistant.ts#L198

There is a "wwww" mistake here.

**Comment by frenck** [comment]
Fix in the current dev branch. 

Thanks for reporting @RSickenberg ❤️ 

../Frenck
