### ISSUE TITLE
Cannot reconnect error

### ISSUE THREAD

**Issue by Frits1980** [keesschollaart81/vscode-home-assistant#333]
I'm starting to think this error from this issue:
https://github.com/hassio-addons/addon-vscode/issues/96

Has everything to do with this code. Why? Because when I disable this extension from vscode, the error never occurs. I know, it could also be the vscode add-on causing it, but since no dev is reacting to it I'm going to post it here too. Maybe it will get the right attention. Or maybe it isn't the add-on where the issue is but this extension. One way or the other I think it needs more attention to solve this.

All my info from my system is in this post: https://github.com/hassio-addons/addon-vscode/issues/96#issuecomment-619573778

Please take some time to look into this before closing this issue.

**Comment by Adorem** [comment]
Just want to tell I also observe the same issue. Is there some others information we can provide to try to understand what's going on?

In the issue reported by @Frits1980 in the hassio addon it seems many of us have encountered this problem too.
The [v2.3.0](https://github.com/hassio-addons/addon-vscode/releases/tag/v2.3.0) of the addon include your version [v1.6.1](https://github.com/keesschollaart81/vscode-home-assistant/releases/tag/v1.6.1) but the latest version [v1.6.5](https://github.com/keesschollaart81/vscode-home-assistant/releases/tag/v1.6.5) do not seems to address this issue.
