### ISSUE TITLE
Pretty much continuous errors

### ISSUE THREAD

**Issue by roopesh** [keesschollaart81/vscode-home-assistant#341]
I have a several errors occuring:
1. I'm sure this is root cause for the rest, but not sure why.  I have a valid cert (Positive SSL / Comodo - Domain Validation)
```
Command 'Home Assistant: Check Configuration (remote!)' resulted in an error (Request checkConfig failed with message: Error: unable to verify the first certificate)
```
2. 
```
(node:1810) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded at Object.determineScalarType (/Users/roopesh/.vscode/extensions/keesschollaart.vscode-home-assistant-1.6.5/node_modules/yaml-language-server/out/server/node_modules/yaml-ast-parser-custom-tags/dist/src/scalarInference.js:71:16) at recursivelyBuildAst (/Users/roopesh/.vscode/extensions/keesschollaart.vscode-home-assistant-1.6.5/node_modules/yaml-language-server/out/server/src/languageservice/parser/yamlParser07.js:77:31) at recursivelyBuildAst (/Users/roopesh/.vscode/extensions/keesschollaart.vscode-home-assistant-1.6.5/node_modules/yaml-language-server/out/server/src/languageservice/parser/yamlParser07.js:53:50) at recursivelyBuildAst (/Users/roopesh/.vscode/extensions/keesschollaart.vscode-home-assistant-1.6.5/node_modules/yaml-language-server/out/server/src/languageservice/parser/yamlParser07.js:41:40) at recursivelyBuildAst (/Users/roopesh/.vscode/extensions/keesschollaart...
```

3.
```
(node:1810) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 593)
```

YAML: (one of many many many)
```
type: vertical-stack
title: Garage
icon: fas:garage
cards:
- type: horizontal-stack
  cards: 
    &light_button
    - type: "custom:button-card" 
      entity: light.garage_interior_lights
      name: Wall
      icon: >
        [[[ 
          if (entity.state == "on")
            return "fal:lightbulb-on"; 
          else if (entity.state == "off") 
            return "fas:lightbulb-slash";
          else 
            return "fas:exclamation-triangle";
        ]]]
      layout: icon_name
      show_state: false
      styles: &button_styles
        icon:
          - align-self: start
        name:
          - justify-self: start
    - <<: *light_button
      entity: light.garage_keypad_a_garage_wa
      name: "Um, wall?"
    - <<: *light_button
      entity: switch.s_garage_overhead_lights
      name: Overhead
- type: horizontal-stack
  cards:
    - <<: *light_button
      entity: switch.s_garage_over_car_light
      name: Over-car
    - <<: *light_button 
      entity: switch.s_garage_over_fridge_light
      name: Fridge
    - <<: *light_button
      entity: light.garage_xmas_lights
      name: XMas
      icon: fal:outlet
- type: horizontal-stack
  cards:
    &lock_button
    - type: "custom:button-card"
      entity: lock.laundry_room_door_lock_new
      name: Laundry
      layout: icon_name
      icon: >
        [[[ 
          if (entity.state == "locked") return "fas:lock"; 
          else if (entity.state == "unlocked") return "fal:lock-open-alt"; 
          else return "fas:exclamation-triangle"; 
        ]]]
      tap_action:
        action: toggle
        haptic: success
      styles: *button_styles
    - <<: *lock_button
      entity: lock.garage_exterior_door_lock
      name: Garage
    - type: "custom:button-card"
      entity: cover.garage_open
      name: Door
      layout: icon_name
      icon: >
        [[[ 
          if (entity.state == "open") 
            return "fal:garage-car";
          else if (entity.state == "closed")
            return "fas:garage";
          else
            return "fas:exclamation-triangle";
        ]]]
      styles: *button_styles
```

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [X] Mac 
- [ ] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:

**Comment by danecreekphotography** [comment]
I'm having the same issue: continuous missing command errors.

`Command 'Home Assistant: Check Configuration (remote!)' resulted in an error (Running the contributed command: 'vscode-home-assistant.homeassistantCheckConfig' failed.)`

**Comment by frenck** [comment]
Stalebot, please keep open.

**Comment by frenck** [comment]
Looked at it briefly, it seems like the Ignore Certificates setting is not honored by API calls (only for the WebSocket connection?)

![image](https://user-images.githubusercontent.com/195327/88651246-c3c9af00-d0c9-11ea-961e-2306ecb297b0.png)


So this might need an adjustment to make that happen.

**Comment by rolandsteinmeyer** [comment]
Also seeing this error. Have tried with and without certificates setting. Using http to HA, have not set up https.

**Comment by rolandsteinmeyer** [comment]
bump

**Comment by tomukasteris** [comment]
I get the same problem. Any resolution on this?

`Command 'Home Assistant: Check Configuration (remote!)' resulted in an error (command 'vscode-home-assistant.homeassistantCheckConfig' not found)`

**Comment by sercanerhan** [comment]
Yes, I'm facing with same issue. 
`Command 'Home Assistant: Check Configuration (remote!)' resulted in an error (command 'vscode-home-assistant.homeassistantCheckConfig' not found)`

**Comment by freynder** [comment]
I'm facing the same issue as well:
`Command 'Home Assistant: Reload Configuration' resulted in an error (command 'vscode-home-assistant.homeassistantReloadCoreConfig' not found)`

**Comment by fstap** [comment]
Same issue running code-server v3.8.0 in docker, tried downgrading to 1.4.0, same issue, no idea what changed

**Comment by hanerd** [comment]
Same here.  No matter what I do, I can't get the language server to run.

**Comment by fstap** [comment]
I fixed it, for some reason the 'out' folder was completely missing from the extension folder (Developer: Show Logs > (Remote) Extension Host). Multiple uninstalls and reinstalls didn't work, I had to copy the folder from my PC to the raspi where I am running code-server on. If anyone needs the files and doesn't want to build it from source, hit me up

**Comment by Inervo** [comment]
> I fixed it, for some reason the 'out' folder was completely missing from the extension folder (Developer: Show Logs > (Remote) Extension Host). Multiple uninstalls and reinstalls didn't work, I had to copy the folder from my PC to the raspi where I am running code-server on. If anyone needs the files and doesn't want to build it from source: https://github.com/fstap/vscode-home-assistant

Do you still have the files for the "out" folder? I have the exact same issue..

**Comment by Drealine** [comment]
@frenck, we have the same problem, I can't load extension > v 1.13 and also command not work.

**Comment by nickelnine** [comment]
> @frenck, we have the same problem, I can't load extension > v 1.13 and also command not work.

Same thing happening here.

**Comment by Drealine** [comment]
> > @frenck, we have the same problem, I can't load extension > v 1.13 and also command not work.
> 
> Same thing happening here.

Resolve the problem by manually install the extension. Maybe it's a problem on the repo of Vscode ?

**Comment by frenck** [comment]
Please stop pinging people...
Also, this issue is closed. It generally helps if one creates an open issue, debugs it, or even better, provides a fix.
