### ISSUE TITLE
Support for external_url: and internal_url: found in HA 0.110.3

### ISSUE THREAD

**Issue by gb53smith** [keesschollaart81/vscode-home-assistant#344]
external_url: and internal_url:  are now required in the homeassistant: section
 I know I was told to fix this myself but the description is too sparse for someone how has never used javascript.  I don`t have npm on my Windows 10.  I don`t know how to customize a Vscode extension.

Otherwise, all my other yaml files pass the schema check.

**Comment by theg00s3** [comment]
I think it has to do with keesschollaart81/vscode-home-assistant/blob/master/src/language-service/src/schemas/homeassistant.ts

**Comment by gb53smith** [comment]
New section changed to:
```
export interface HomeAssistantComponent {
    name?: string;
    latitude?: string | number;
    longitude?: string | number;
    elevation?: string | number;
    unit_system?: "metric" | "imperial";
    time_zone?: string;
    external_url?: string;
    internal_url?: string;
    whitelist_external_dirs?: string[];
    customize?: CustomizeComponent | IncludeTags;
    customize_domain?: any;
    customize_glob?: any;
    packages?: Array<HomeAssistantRoot> | NamedPackageInclude | IncludeTags;
    auth_providers?: AuthProviders[] | IncludeTags;
    auth_mfa_modules?: Array<any> | IncludeTags;
}
```
Problem is how to get this change back into the vscode extension.  I tried install nodejs on my Windows PC but it was a disaster, messing up my existing Python installation.   I had some success with Docker using a node image and used these steps:
Clone the repository to my local github folder.
```git clone https://github.com/keesschollaart81/vscode-home-assistant```
Start docker container in interactive mode in vscode-home-assistant
```docker run --name vscode -it -v ${PWD}:/usr/src/app -w /usr/src/app node:14.4.0 bash```
Add missing node_modules/tslint
```npm install tslint```
```npm install```
```npm run schema ```
I got the new schema in ```vscode-home-assistant\src\language-service\src\schemas\json```
I was unable to get it working in the vscode extension debugger.
Attached is a log file showing some of the error messages.  [log.txt](https://github.com/keesschollaart81/vscode-home-assistant/files/4732658/log.txt)
It is a difficult process maintaining this extension.  

Maybe someone, more talented than I,
could clean this up with a simple Docker image to run.

**Comment by theg00s3** [comment]
[This file](https://github.com/theg00s3/vscode-home-assistant/raw/with-extension/vscode-home-assistant-1.6.5.vsix) (in theory) should work. You go to extensions, press the triple dot button, and click "Install from VSIX"

I've also requested to merge the changes with the codebase, so that when the official extension is updated, it will have these changes.

**Comment by theg00s3** [comment]
That file seems to overwrite the official extension, which means that when the extension is officially updated on GitHub (with a version bump) it'll update on your copies of VS Code as well

**Comment by gb53smith** [comment]
Thankyou theg00s3.  The VSIX installation worked so your proposed merge should be OK for the next release.   I wish that the readme had more details how to make a VSIX.
