### ISSUE TITLE
internal_url and external_url marked as invalid

### ISSUE THREAD

**Issue by donkristo** [keesschollaart81/vscode-home-assistant#359]
I am using internal_url and external_url in my configuration.yaml file and the extension is telling me these properties are not allowed. I have no clue how to fix this in the schema so I rather open this issue.

![image](https://user-images.githubusercontent.com/10496260/85195475-1d70d980-b2d3-11ea-869b-93b5f7a50c52.png)

[https://www.home-assistant.io/docs/configuration/basic/](url)

Thank you

**Comment by tomlut** [comment]
Duplicate:

https://github.com/keesschollaart81/vscode-home-assistant/issues/344

**Comment by donkristo** [comment]
Sorry for the duplicate. Obviously I've only searched open issues before I created a new issue.
