### ISSUE TITLE
False problems?

### ISSUE THREAD

**Issue by kloggy** [keesschollaart81/vscode-home-assistant#36]
I think the extension might be highlighting some false problems.

1. input_boolean with nothing else defined e.g. 
```
input_boolean:
  my_boolean1:

  my_boolean2:
```

2. I find that `wait_template` often (always?) gets highlighted as a problem
![image](https://user-images.githubusercontent.com/38220016/57973929-4a540e00-79a8-11e9-864a-366c2ad009b9.png)
![image](https://user-images.githubusercontent.com/38220016/57973941-635cbf00-79a8-11e9-849e-ca9ac8e00336.png)

**Comment by keesschollaart81** [comment]
Thanks. Fixed in v0.6.1.

**Comment by kloggy** [comment]
Thanks, I don't know if it is right to comment or to have started a new issue but I have just found another small one.
![image](https://user-images.githubusercontent.com/38220016/57999441-5980ac00-7acd-11e9-8710-b7881211bde4.png)
To be honest it is probably more correct to have `continue_on_timeout: false` (no quotes) but I seem to have a mix in my config and as it is valid either way I thought you'd like to know.
Butif it is **_definitely_** more correct without quotes feel free to tell me and leave the extension as it is.
