### ISSUE TITLE
Upgrade to GitHub's dependabot

### ISSUE THREAD

**Issue by frenck** [keesschollaart81/vscode-home-assistant#372]
I've noticed this repository uses the dependabot-preview, this one is deprecated and being replaced by GitHub's built-in version.

To upgrade, go to dependabot.com, login, and click to create a configuration file.
That will open up a PR, once that is merged, the upgrade is complete.

(GitHub will handle it automatically for you at that point).

**Comment by frenck** [comment]
Oh, process any open PRs from dependabot first, or you'll end up with duplicated 😉

**Comment by keesschollaart81** [comment]
Done!
