### ISSUE TITLE
Personal CA - refused when trying to send command

### ISSUE THREAD

**Issue by m3xiz** [keesschollaart81/vscode-home-assistant#373]
Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X ] Windows 
- [] Mac 
- [ ] Linux 

I'm accessing my files:
- [] From local disk 
- [ ] Via remote SSH 
- [x ] Smb
- [ ] Other:  

My Home Assistant is using a certificate coming from my personal PKI. the root CA certificate is installed in all systems and I have no issue connecting on the web interface of Home  Assistant.

When configuring the extension, I can reach home assistant and have all checking working correctly: no error message when configuring the add-on but I need to check the box for the untrusted certificate. If I do not do this, there is complain that there is an untrusted certificate. I find this strange as my root certificate is trusted in windows.

When trying to send command like configuration check, the add-on complain about an untrusted certificate and fails.

If I remove the certificates in HA, all is working fine.

What do I do wrong?

Thanks in advance

**Comment by frenck** [comment]
This issue can be closed.

This is not an extension issue, but a VSCode issue that doesn't honor certificates trusted by Windows itself.

There are some workarounds available, e.g., <https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca>

**Comment by m3xiz** [comment]
I did not know. thanks for the info. I will try that asap
