### ISSUE TITLE
1.7.1 : Template Renderer always output [object Object]

### ISSUE THREAD

**Issue by Guyohms** [keesschollaart81/vscode-home-assistant#379]
Please include the related YAML code:

```YAML
[{{states('sensor.date_time')}}]
```

Find my Home Assistant Configuration here:
---

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [X] Windows 
- [ ] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [X] Smb
- [ ] Other:  

Like the title says, I cannot use the new Template Render feature as it always results in `[object Object]`
Example Output:
```
[16 h 36 min 47 s] Rendering template:
[{{states('sensor.date_time')}}]

Result:
[object Object]
```

The connection to Home Assistant seems good because I see this in the logs:
```
[Home Assistant Language Server(7820)] Started and initialize received
Connecting to Home Assistant...
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant... Tries left: 3
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
Connected to Home Assistant
Discover all configuration files because file://hassio/config/automations.yaml got updated and new files were found...
Applying schema's to 9 of your configuration files...
Schema's updated!
```

**Comment by frenck** [comment]
Fixed in #411
