### ISSUE TITLE
More HA-related autocompletions

### ISSUE THREAD

**Issue by fantomnotabene** [keesschollaart81/vscode-home-assistant#4]
Hi there, great work ;)
What do you think about autocompletion for platforms (e.g. in triggers) and services?

**Comment by keesschollaart81** [comment]
Services I implemented yesterday and released just before you created this issue. 

I'll leave this issue open to keep track of the implementation of triggers!

**Comment by fantomnotabene** [comment]
Maybe, autocomplete existing keys from `secrets.yaml` after `!secret `?

**Comment by krihil** [comment]
Exellent work! Thank you. As an improvement for the future, auto completion of available Lovelace cards would also be really helpful.
