### ISSUE TITLE
False errors

### ISSUE THREAD

**Issue by kloggy** [keesschollaart81/vscode-home-assistant#40]
I have found two more small ones.
![image](https://user-images.githubusercontent.com/38220016/58371294-25abe900-7f08-11e9-9a48-ac25db62efcb.png)
To be honest it is probably more correct to have continue_on_timeout: false (no quotes) but I seem to have a mix in my config and as it is valid either way I thought you'd like to know.
But if it is definitely more correct without quotes feel free to tell me and leave the extension as it is.

Also
you don't allow for ThomasLoven's custom popup card:
![image](https://user-images.githubusercontent.com/38220016/58371350-76234680-7f08-11e9-8aa0-182548ea579b.png)

**Comment by keesschollaart81** [comment]
Fixed with 0.6.2
