### ISSUE TITLE
The autocomplete just doesn't work here!

### ISSUE THREAD

**Issue by orickcorreia** [keesschollaart81/vscode-home-assistant#400]
![image](https://user-images.githubusercontent.com/58919667/87885267-b2561800-c9e2-11ea-9435-355fa006f446.png)

The autocomplete just doesn't work here!
It does not appear automatically, nor when I press "Control + Space". It keeps loading forever! The autocomplete entities appeared very rarely. The most curious thing is that the connection is apparently made, because I can restart the home assistant using the Command Palette.

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [X] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [X] Smb
- [ ] Other:

**Comment by frenck** [comment]
Restart works on a different mechanism, so that is not related.

It here anything in the Home Assistant extension output when this happens?

**Comment by orickcorreia** [comment]
> Restart works on a different mechanism, so that is not related.
> 
> It here anything in the Home Assistant extension output when this happens?

The problem was just resolved after I installed this extension together: https://marketplace.visualstudio.com/items?itemName=liximomo.sftp

**Comment by frenck** [comment]
ok, do I understand correctly that this issue can be closed now?
