### ISSUE TITLE
Incorrect type. Expected "object"

### ISSUE THREAD

**Issue by oncleben31** [keesschollaart81/vscode-home-assistant#41]
I use a config like @frenck using a lot of `!include`

I have a `script.yaml` file with
```
script: !include_dir_named ../../scripts
```
This way the name of the files in folder `script` is used as the entity_id of each script. But the home assistant add-on see errors in all files of this folder with the error message in title of the issue.
Home Assistant raises no error with those files and work as expected.
You can see example [in my repo](https://github.com/oncleben31/home-assistant-config/tree/vacuum/scripts).

**Comment by keesschollaart81** [comment]
Thanks for bringing this up! It should be fixed in 0.6.2 which I just released. Let me know if I missed something!

**Comment by oncleben31** [comment]
I confirm. No more error. Thank you for the fix.

**Comment by tal** [comment]
I'm encountering this issue myself.

when I use `!include_dir_named` it doesn't work, it's got the `Incorrect type. Expected "object".` error.

If I use `!include_dir_named` (with appropriate namespacing of each script) it gets the correct typing.

**Comment by Plaatjesdraaier** [comment]
I have the same issue here after hardlinking the scripts.yaml (workaround) ref https://github.com/home-assistant/core/issues/38456

**Comment by frenck** [comment]
@Plaatjesdraaier That has absolutely nothing to do with this discussion/bug report or this repository.

**Comment by Plaatjesdraaier** [comment]
Ok, strange. It happened at the same time I hardlinked scripts.yaml  (and still)
