### ISSUE TITLE
Feature Request: AppDaemon Support

### ISSUE THREAD

**Issue by apop880** [keesschollaart81/vscode-home-assistant#43]
I had thoughts around trying to attempt this myself, but it looks like you've added quite a bit of functionality since I forked your code and it may be a little more than I can chew at this point.

But what I'd be very interested in is being able to leverage what you've already done around entity and service auto-completion and using it in AppDaemon. So, I can think of the following things it would need:

- Support for .py files in the appdaemon directory
- If a .py file is open, provide service auto-completion support. Service call always begins with `self.call_service("domain/service_name"`, so for example `self.call_service("light/turn_on"`
- Entities are generally referenced with the variables `entity` or `entity_id`. So, auto-complete after any of the following are typed would be desired:
  - `entity = "`
  - `entity == "`
  - `entity_id = "`
  - `entity_id == "`

I'm definitely a novice when it comes to VS Code extensions but I'd be happy to help as much as possible.

**Comment by SilverWx** [comment]
Good idea !

**Comment by frenck** [comment]
While it sounds like that, it really isn't.

Combining multiple languages isn't advised. The Home Assistant configuration uses YAML, while AppDaemon is Python based. It would be a better move to create a separate extension that hooks into the Python extensions to provide this behavior.
