### ISSUE TITLE
mdi icons inserted incorrectly

### ISSUE THREAD

**Issue by kloggy** [keesschollaart81/vscode-home-assistant#45]
Is the mdi Explorer part of this extension?
Using "Inset Icon Into Editor" inserts it as:

`mdi-alert` instead of 
`mdi:alert`

Also on a similar note, any idea when the file icons will be updated?

**Comment by keesschollaart81** [comment]
MDI icons is a separate extension: https://github.com/lukas-tr/vscode-materialdesignicons-intellisense
Icons work, for a week now: you might have to [reinstall / reset the file icon theme](https://github.com/vscode-icons/vscode-icons/pull/2054#issuecomment-496012967)
