### ISSUE TITLE
HACS token error when using secret

### ISSUE THREAD

**Issue by apop880** [keesschollaart81/vscode-home-assistant#451]
After upgrading to the latest version of this extension (via the Home Assistant VS Code add-on), I'm getting the below error if my HACS token is in my secrets file. This did not error previously (and is still fully functional Home Assistant). If I paste the access token directly into configuration.yaml, the error goes away.

![image](https://user-images.githubusercontent.com/41379678/88821126-e15d4e00-d187-11ea-8c3a-45241cb47536.png)

**Comment by andrepia** [comment]
Same here. Any progress or workaround?
Thanks!
