### ISSUE TITLE
Material Design Icons Intellisense

### ISSUE THREAD

**Issue by apop880** [keesschollaart81/vscode-home-assistant#46]
I was using this extension when I was working with Lovelace YAML files designated as the YAML language in VS Code, but since switching to designate them as Home Assistant files, the MDI extension no longer suggests icons using Intellisense.

**Comment by apop880** [comment]
Never mind, I was able to update settings for the MDI extension. I'll log an issue over there.

**Comment by raulvasquez** [comment]
@apop880  How did you fix this?

**Comment by apop880** [comment]
@raulvasquez You need to go into the settings for the Material Design Icons Intellisense extension, scroll down to the last setting, `Materialdesignicons Intellisense: Selector`, and click "Edit in settings.json". And then add `"home-assistant"` to `"materialdesigniconsIntellisense.selector"`. It should look something like this:

```json
    "materialdesigniconsIntellisense.selector": [
        "javascript",
        "typescript",
        "javascriptreact",
        "typescriptreact",
        "html",
        "vue-pug",
        "vue-html",
        "vue",
        "ng-template",
        "yaml",
        "home-assistant"
      ],
```

I have opened a PR (https://github.com/lukas-tr/vscode-materialdesignicons-intellisense/pull/4) to have this added to the Material Design Icons Intellisense extension as a default.
