### ISSUE TITLE
High CPU usage 

### ISSUE THREAD

**Issue by roflcoopter** [keesschollaart81/vscode-home-assistant#48]
Ever since the version which added "Go to definition" for include files, the CPU usage has skyrocketed for me.

When i am editing a file and saving it, it maxes out one core on my Intel NUC and it is really slow to perform the schema-check.

I am not getting any errors, just a very slow VSCode. Is there any other information i can provide you with to help troubleshoot?

EDIT: I monitored the CPU using top, and as soon as i start to edit a .yaml file the CPU usage goes through the roof so its not just on saving the file. It seems to be the syntax-check which is causing the problem.

In contrast, if i edit a python program i get at most 40% CPU usage, while this extension showed at most 164% CPU usage

**Comment by keesschollaart81** [comment]
Hmmm, do you have a big configuration (your config is not public, right?), like > 100 files? What kind of device do you use?

**Comment by roflcoopter** [comment]
Sorry for late reply,

No it is not public sadly
I wouldnt call it that big, i have around 60 yaml files in total.
I do however use a lot of packages in my config, and a lot of includes in my lovelace setup.

I am running on an Intel NUC7i5BNH

**Comment by keesschollaart81** [comment]
Ah, is VS Code running in Hassio?

**Comment by roflcoopter** [comment]
Its running in a docker container, but not through Hassio

**Comment by keesschollaart81** [comment]
Good to know, I don't have a NUC around to test, I've only tested it on Windows and Mac. Let me set that up and test it, I think this weekend.

**Comment by roflcoopter** [comment]
This is still a huge issue for me. makes the temperature on my NUC go crazy.
This is what i see in the output when i open a yaml file.
```
Discover all configuration files because file:///workspace/hass/packages/hadockermon.yaml got updated and new files were found...
Cannot find the files in folder .
The include could not be resolved because no file(s) found in 'packages' included with 'include_dir_named' from 'dev-hass/configuration.yaml'
The include could not be resolved because no file(s) found in 'packages' included with 'include_dir_named' from 'dev-hass/configuration.yaml'
File '/workspace/dev-hass/customize.yaml' could not be parsed, it was referenced from path 'configuration.yaml/homeassistant/customize'.This file will be ignored. Error(s): 
 - Empty yaml
File '/workspace/dev-hass/groups.yaml' could not be parsed, it was referenced from path 'configuration.yaml/group'.This file will be ignored. Error(s): 
 - Empty yaml
File '/workspace/dev-hass/scripts.yaml' could not be parsed, it was referenced from path 'configuration.yaml/script'.This file will be ignored. Error(s): 
 - Empty yaml
File '/workspace/hass/packages/flic.yaml' could not be parsed, it was referenced from path 'figuration.yaml/homeassistant/packages'.This file will be ignored. Error(s): 
 - YAMLSemanticError: Implicit map keys need to be followed by map values (Line: 12)
File '/workspace/magnus_old_config/.homeassistant/customize.yaml' could not be parsed, it was referenced from path 'ld_config/.homeassistant/configuration.yaml/homeassistant/customize'.This file will be ignored. Error(s): 
 - Empty yaml
File '/workspace/magnus_old_config/.homeassistant/groups.yaml' could not be parsed, it was referenced from path 'ld_config/.homeassistant/configuration.yaml/group'.This file will be ignored. Error(s): 
 - Empty yaml
Applying schema's to 62 of your configuration files...
Schema's updated!
```

As you can see it seems to be scanning my entire workspace for files, which is not very efficient since i have **a lot** if files.
Isnt it enough to apply the schema to only the opened yaml file?

My main configuration is /workspace/hass, but it is also scanning two other folders which is not currently in use.
An option to specify the root folder of the configuration would be nice, or for the scan to respect the file association setting
```
   "files.associations": {
      "/workspace/hass/**/*.yaml": "home-assistant",
    }
```

Its also kind of useless in this state since loading the entities/applying the schema takes around 1 minute which makes development really slow.
