### ISSUE TITLE
Can't insert token on mac

### ISSUE THREAD

**Issue by fliphess** [keesschollaart81/vscode-home-assistant#5]
Hey Kees! 

I'm not sure if this is is a quirk in the extension or something in Code itself.

When I install the plugin in Code on mac and select the option to "configure now", I'm not really able to configure the plugin:

Pasting the home assistant url goes fine, no problems there, but as soon as I move the focus from the editor to another window (alt+tab) to copy paste the long lived access token, the configuration "window" (The one input line), pops away and I can't paste my token anymore... 

The token is too long to remember, so copy pasting would be highly preferred :)

I think will be able to insert the token somewhere in some file, so I'll find a workaround, but it would be nice if it worked :)

Thanks for the effort of creating this lovely plugin, I haven't used it yet, but I love it already 👍 

EDIT: Typo's

**Comment by eggman0131** [comment]
Similar issue on my PC.  

So hit the manage cog icon bottom left, then settings, extensions, home-assistant-config-helper, enter the code there.

![image](https://user-images.githubusercontent.com/45142867/54716011-b18e4700-4b4c-11e9-8b03-d69717411149.png)

**Comment by keesschollaart81** [comment]
thanks @mickdekkers
