### ISSUE TITLE
"include_dir_merge_named" highlighted as "unknown tag"

### ISSUE THREAD

**Issue by pbavinck** [keesschollaart81/vscode-home-assistant#501]
# Problem/Motivation
YAML validation does not recognize the allowed construct ```include_dir_merge_named``` in configuration.yaml. Even though this is supported by [Home Assistant](https://www.home-assistant.io/docs/configuration/splitting_configuration/#advanced-usage).
(I do not know if the other advanced constructs are not supported either)

## Expected behavior
Nothing highlighted as invalid, no error

## Actual behavior
Configuration lines that contain the mentioned construct are highlighted with an error and marks the yaml file as invalid (without consequence I might add, but still, annoying).
![image](https://user-images.githubusercontent.com/4839523/90522234-c15bf180-e16b-11ea-8d30-d2d9aae9c536.png)

## Steps to reproduce
Example based on themes subfolder
1. create a subfolder _themes/_
2. put themes config files in this subfolder
3. use in configuration.yaml:
```yaml
frontend:
  themes: !include_dir_merge_named themes/
```

**Comment by frenck** [comment]
Which version of the Home Assistant VSCode extension are you using?

As I'm not able to reproduce this:

![image](https://user-images.githubusercontent.com/195327/91666858-aa6cb600-eb00-11ea-8f98-14392ff1ad1d.png)
 
To show validation actually works, this is of course invalid:

![image](https://user-images.githubusercontent.com/195327/91666869-b9536880-eb00-11ea-9a1a-f890cc61c928.png)

**Comment by pbavinck** [comment]
v2.4.0
BTW same problem with ```include_dir_merge_list```.
![image](https://user-images.githubusercontent.com/4839523/91729576-0e48ba80-eba5-11ea-9be8-4f8ae7f430ee.png)
In the screenshot you can see that the "normal" include functions fine

**Comment by frenck** [comment]
Sounds like a local configuration issue to VSCode to me.

In the case of the add-on, you could try to reset its settings. Please refer to the add-on manual on how to do that.

**Comment by pbavinck** [comment]
In Home Assistant I removed and reinstalled the VS Code addon. Problem solved.
As an FYI - a was not loading any extensions, changed configs or settings. That's why I was able to simply reinstall.

Thanks.

**Comment by frenck** [comment]
Not sure what it was in that case, but glad you've got it resolved 👍
