### ISSUE TITLE
Extra space is added if entity is entered after a dash (-)

### ISSUE THREAD

**Issue by wxt9861** [keesschollaart81/vscode-home-assistant#6]
When using the extension to autofill after a dash (-) an extra space is added. Displayed in the screenshot.

![Screen Shot 2019-03-20 at 6 16 38 PM](https://user-images.githubusercontent.com/34514130/54722964-56ecef00-4b3c-11e9-889c-b29891d0f873.png)

**Comment by keesschollaart81** [comment]
Fixed with https://github.com/keesschollaart81/vscode-home-assistant/commit/d1b488dc6479ab85dbd789315f67a522a5e75a52

**Comment by keesschollaart81** [comment]
Fixed with https://github.com/keesschollaart81/vscode-home-assistant/commit/d1b488dc6479ab85dbd789315f67a522a5e75a52
