### ISSUE TITLE
How to render jinja template

### ISSUE THREAD

**Issue by matejdro** [keesschollaart81/vscode-home-assistant#602]
Hello,

Sorry, I must be blind here, but I cannot find the template rendering feature. Image in the `README.MD` under "Render templates" titles appears to be completely unrelated.

How do I activate this feature?

Thanks.

**Comment by frenck** [comment]
Select the text/template code you want to render, right click with your mouse -> render template.

**Comment by matejdro** [comment]
Doh it was that simple. Thanks!

Any chance you could fix that image in the README? Thanks.
