### ISSUE TITLE
Warning: require() of ES modules is not supported

### ISSUE THREAD

**Issue by poldim** [keesschollaart81/vscode-home-assistant#621]
Clean install of VS code _(Version: 1.49.0)_ and extension (_v1.9.0 via VS Code Marketplace_), configured HA via LAN IP:PORT and provided token.  Upon launch, I get the below error:
```
(node:53435) Warning: require() of ES modules is not supported.
require() of /Users/poldim/.vscode/extensions/keesschollaart.vscode-home-assistant-1.9.0/node_modules/home-assistant-js-websocket/dist/haws.umd.js from /Users/poldim/.vscode/extensions/keesschollaart.vscode-home-assistant-1.9.0/out/language-service/src/home-assistant/haConnection.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename haws.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/poldim/.vscode/extensions/keesschollaart.vscode-home-assistant-1.9.0/node_modules/home-assistant-js-websocket/package.json.
```

Log shows connection established but above warning still persists
```
[Home Assistant Language Server(53837)] Started and initialize received
Cannot find the files in folder homebridge/node_modules/homebridge-dummy/node_modules/.bin
Cannot find the files in folder node-red/node_modules/.bin
Connecting to Home Assistant...
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant... Tries left: 3
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
Connected to Home Assistant
Applying schemas to 37 of your configuration files...
Schemas updated!
```

![image](https://user-images.githubusercontent.com/16869713/93004877-1affd380-f500-11ea-8d12-8ec5d37d4a43.png)

No related YAML to provide.
Find my Home Assistant Configuration here:  **Repo is private**

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [X] Mac 
- [ ] Linux 

I'm accessing my files:
- [ ] From local disk 
- [ ] Via remote SSH 
- [ X ] SMB
- [ ] Other:

**Comment by CeeWeasel** [comment]
Can confirm this issue is also occurring on VSCode in Windows 10. The error message received is the same.

**Comment by rodakswe** [comment]
Can also confirm this.
It started now when I updated VS Code to 1.49.0, no issues before the update.

**Comment by andrepia** [comment]
Same here. Exact same scenario as @poldim.

**Comment by xbmcnut** [comment]
Ditto with v1.9.0

Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by poldim** [comment]
@keesschollaart81 is there any additional info you need to help diagnose this error?

**Comment by CineMAC-HA** [comment]
same here. issue in v1.8.0 and v1.9.0

macOS Catalina 10.15.6

Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:21:17.533Z (2 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by jaddel** [comment]
Same for me:

`(node:14527) Warning: require() of ES modules is not supported. require() of /Users/xxxxxxxxxx/.vscode/extensions/keesschollaart.vscode-home-assistant-1.9.0/nodemodules/home-assistant-js-websocket/dist/haws.umd.js from /Users/xxxxxxxxx/.vscode/extensions/keesschollaart.vscode-home-assistant-1.9.0/out/language-service/src/home-assistant/haConnection.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename haws.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/xxxxxxxxxx/.vscode/extensions/keesschollaart.vscode-home-assistant-1.9.0/nodemodules/home-assistant-js-websocket/package.json.`

**Comment by Tim-Dixon** [comment]
Likewise:
OS: Windows 10 

(node:14072) Warning: require() of ES modules is not supported. require() of c:\Users\xxxxxxxx\.vscode\extensions\keesschollaart.vscode-home-assistant-1.9.0\node_modules\home-assistant-js-websocket\dist\haws.umd.js from c:\Users\xxxxxxx\.vscode\extensions\keesschollaart.vscode-home-assistant-1.9.0\out\language-service\src\home-assistant\haConnection.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename haws.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from c:\Users\xxxxxxx\.vscode\extensions\keesschollaart.vscode-home-assistant-1.9.0\node_modules\home-assistant-js-websocket\package.json.

**Comment by Salvora** [comment]
same here

**Comment by djryan012** [comment]
Windows 10 with VS 1.49.1

(node:3632) Warning: require() of ES modules is not supported. require() of c:\Users\David\.vscode\extensions\keesschollaart.vscode-home-assistant-1.9.0\node_modules\home-assistant-js-websocket\dist\haws.umd.js from c:\Users\David\.vscode\extensions\keesschollaart.vscode-home-assistant-1.9.0\out\language-service\src\home-assistant\haConnection.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename haws.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from c:\Users\David\.vscode\extensions\keesschollaart.vscode-home-assistant-1.9.0\node_modules\home-assistant-js-websocket\package.json.

**Comment by loaonline** [comment]
Same error here.  Let us know if any other information will help.

Pop_OS! (Ubuntu) 20.04 LTS,  VSCode 1.49.2  

(node:3621) Warning: require() of ES modules is not supported.
require() of /home/****/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.9.0/node_modules/home-assistant-js-websocket/dist/haws.umd.js from /home/****/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.9.0/out/language-service/src/home-assistant/haConnection.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename haws.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/****/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.9.0/node_modules/home-assistant-js-websocket/package.json.

**Comment by ittchmh** [comment]
I have same error: Warning: require() of ES modules is not supported

Also in source code I see error: Incorrect type. Expected "string". in /root/.vscode-server/extensions/keesschollaart.vscode-home-assistant-1.9.0/node_modules/home-assistant-js-websocket/package.json

![Code_exFxor8Vof](https://user-images.githubusercontent.com/7413426/94337583-3dabe500-fff4-11ea-908b-0ded4e043168.png)

**Comment by frenck** [comment]
Yeah, this is a confirmed issue, showing up on the latest VSCode (1.49+).
That release updated electron and nodejs, and now it explodes. 

The upstream package (home-assistant-js-websocket) has been adjusted for this situation (as code-server did this upgrade before VSCode), however, it seems to be failing (while code-server works).

I personally don't see the issue and set out some questions with the codeowners of the upstream home-assistant-js-websocket package.

**Comment by waltzy34** [comment]
Same here 
`(node:14628) Warning: require() of ES modules is not supported. require() of c:\Users\1c3gu\.vscode\extensions\keesschollaart.vscode-home-assistant-1.9.0\node_modules\home-assistant-js-websocket\dist\haws.umd.js from c:\Users\1c3gu\.vscode\extensions\keesschollaart.vscode-home-assistant-1.9.0\out\language-service\src\home-assistant\haConnection.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename haws.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from c:\Users\1c3gu\.vscode\extensions\keesschollaart.vscode-home-assistant-1.9.0\node_modules\home-assistant-js-websocket\package.json.`
VSC 1.49.2, HACH v1.9.0, Windows 10, Using samba on HA in docker

**Comment by keesschollaart81** [comment]
Awesome, thanks @frenck and @bramkragten!
