### ISSUE TITLE
Customize.yaml device_class issue

### ISSUE THREAD

**Issue by velaar** [keesschollaart81/vscode-home-assistant#659]
It seems customize.yaml will only accept some of the values, creating an unnecessary warning. 
![image](https://user-images.githubusercontent.com/4062230/94347590-92a32780-0003-11eb-8212-7d494a0f837a.png)
The configuration is valid though.

**Comment by frenck** [comment]
Well, the `co2` and `co` device classes for sensors, are actually invalid. 

<https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/__init__.py#L37>

The device classes for the media player are indeed missing in the extension.

**Comment by velaar** [comment]
@frenck homekit documentation explicitly suggests two use co2 and co (among other)

See here:
https://www.home-assistant.io/integrations/homekit/
![image](https://user-images.githubusercontent.com/4062230/94488556-d1c2ab80-01b0-11eb-85f8-2f1452cc896d.png)

**Comment by frenck** [comment]
Well, that is either wrongly documented or a bug in the HomeKit integration, the device class simply doesn't exist in Home Assistant's core components as you can see in the linked sensor code above.
