### ISSUE TITLE
"device_class:" "value not accepted" warning in configuration.yaml with valid value

### ISSUE THREAD

**Issue by THATDONFC** [keesschollaart81/vscode-home-assistant#711]
# Problem/Motivation

I'm seeing a warning `"value not accepted"` for `device_class: outlet` when I have my `configuration.yaml` open in the vscode add-on.

## Expected behavior

I expect to not see this warning. The value was set via the UI so it should be valid.

## Actual behavior

I see the warning.

## Steps to reproduce

Go to configuration > customizations in the UI and select an outlet/switch entity. Customize the device class to be an outlet. Open `configuration.yaml` in the vscode add-on to see the warning. 

## Proposed changes

This is merely a visual annoyance for a specific case. This doesn't actually prevent me from doing anything. Still, I don't think this warning should be displayed for a value that is in fact valid. 

![Screen Shot 2020-10-09 at 6 13 43 AM](https://user-images.githubusercontent.com/24759498/95588660-89995980-09f8-11eb-9f5f-6f0450308e74.png)
![Screen Shot 2020-10-09 at 6 13 29 AM](https://user-images.githubusercontent.com/24759498/95588663-8a31f000-09f8-11eb-824f-d35be24ee3f1.png)

**Comment by frenck** [comment]
Found the issue, will be fixed with PR #712
