### ISSUE TITLE
MQTT Device Tracker devices - expected array

### ISSUE THREAD

**Issue by apop880** [keesschollaart81/vscode-home-assistant#729]
![image](https://user-images.githubusercontent.com/41379678/96193114-15d1e200-0f0d-11eb-8eab-ec5bd519fc80.png)

This appears to be an issue that was recently introduced, as I never got an error for this before. I double-checked the documentation for MQTT device tracker and a list is what's expected, so my configuration is valid: https://www.home-assistant.io/integrations/device_tracker.mqtt/

**Comment by etcg** [comment]
I get the same error. My config is valid and working without problems.

**Comment by zphaze** [comment]
Glad to see this is already reported, I noticed this error today while adding something to my config. Config check passes with no issues.

**Comment by frenck** [comment]
Confirmed. Fixed in #794
