### ISSUE TITLE
Missing property "tilt_opened_value" 

### ISSUE THREAD

**Issue by jokerigno** [keesschollaart81/vscode-home-assistant#731]
Hi,

I noticed this error message. 

Looking at docs the tilt_opened_value is not a required property to set a mqtt cover in HA.

Can you please confirm?

TY

**Comment by frenck** [comment]
please provide a piece of sample YAML code for debugging and testing.

Thanks 👍

**Comment by jokerigno** [comment]
Here it is:

`
cover:
  - platform: mqtt
    name: "Tapparella Cucina"
    availability_topic: "tapparellacucina/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    position_topic: "tapparellacucina/stat/SHUTTER1"
    position_open: 100
    position_closed: 0
    set_position_topic: "tapparellacucina/cmnd/shutterposition"
    value_template: "{{ value | int }}"
    command_topic: "tapparellacucina/cmnd/backlog"
    payload_open: "SHUTTEROPEN"
    payload_close: "SHUTTERCLOSE"
    payload_stop: "SHUTTERSTOP"
    device_class: shutter
    qos: 0`

**Comment by frenck** [comment]
Thanks, @jokerigno 👍 

Fixed it in #739, should be available in the next release.

PS:

```yaml
value_template: "{{ value | int }}"
```

**Comment by jokerigno** [comment]
One is glade to be of service
