### ISSUE TITLE
Feature request: Add Jinja2 inside yaml files support

### ISSUE THREAD

**Issue by pedrolamas** [keesschollaart81/vscode-home-assistant#78]
Just like it says on the title, I just think it would be great to have full color-coding support for Jinja2 snippets inside the .yaml files.

**Comment by definitio** [comment]
It's not implemented yet, too early to close.

**Comment by definitio** [comment]
It's not implemented yet, too early to close.

**Comment by deluxestyle** [comment]
fully support this request

**Comment by definitio** [comment]
It's not implemented yet, too early to close.

**Comment by definitio** [comment]
It's not implemented yet, too early to close.

**Comment by definitio** [comment]
It's not implemented yet, too early to close.

**Comment by frenck** [comment]
I think this is actually fairly easy to do... needs a bit of fiddling, but, yeah, should be possible

**Comment by definitio** [comment]
It's not implemented yet, too early to close.

**Comment by definitio** [comment]
@keesschollaart81 Can you open it again?

**Comment by kubawolanin** [comment]
This issue can be closed I think 😎

**Comment by frenck** [comment]
Absolutely! Thanks, @kubawolanin 👍

**Comment by pedrolamas** [comment]
Thanks @frenck! 😁

**Comment by frenck** [comment]
Don't thank me, this is awesome work by @kubawolanin!
