### ISSUE TITLE
Glance card: Incorrect type. Expected "object".

### ISSUE THREAD

**Issue by definitio** [keesschollaart81/vscode-home-assistant#789]
![Screenshot_20201104_133925](https://user-images.githubusercontent.com/37266727/98094911-56d16c80-1ea3-11eb-94b3-facdc34facc2.png)
`Incorrect type. Expected "object".`

**Comment by oncleben31** [comment]
I have the same message for my scripts who are in different files using `script: !include_dir_named ../scripts` in config.
If you need an example to reproduce: https://github.com/oncleben31/home-assistant-config/blob/master/config/scripts/routines/stop_vacuum_workday_sequence.yaml
