### ISSUE TITLE
Allow activation when configuration.yaml or ui-lovelace.yaml are in subfolder

### ISSUE THREAD

**Issue by PedroLamas** [keesschollaart81/vscode-home-assistant#79]
If one uses a repo where home-assistant config in a subfolder, the plugin won't activate as it just looks for `configuration.yaml` and `ui-lovelace.yaml` in the root folder.

This is an example where this can be experienced: https://github.com/PedroLamas/nanopineo2-docker-config

Ideally, I believe that subfolders should be checked for these files.

**Comment by keesschollaart81** [comment]
Awesome, I didn't know this was possible. Will merge after some testing when I'm back from holiday (1,5 week).

**Comment by keesschollaart81** [comment]
Closing for now with comments in the related PR #80.
