### ISSUE TITLE
Upload to Open VSX

### ISSUE THREAD

**Issue by matejdro** [keesschollaart81/vscode-home-assistant#809]
Open source builds of VS Code on some Linux distributions use Open VSX instead of VS marketplace to install extensions: https://bugs.archlinux.org/task/67780

Any chance you could upload this extension to Open VSX?

Thanks.

**Comment by frenck** [comment]
There is no need to use that, as it is already on the marketplace (and for download as well). The code is available in this repo and the vsix files are attached to releases.

The add-on repository (your created an issue on before) is a great example of a third-party vscode compatible IDE (`code-server` to be specific) using this extension downloaded directly from the marketplace.

**Comment by matejdro** [comment]
While I agree that it is not strictly necessary, it is convenient as it having it on the Open VSX repo allows for all of those third party compatible IDEs to automatically update the extension whenever new version arrives.

**Comment by chpego** [comment]
> There is no need to use that, as it is already on the marketplace (and for download as well). The code is available in this repo and **the vsix files are attached to releases**.
> 

@frenck since version 1.14, the file is no longer included in the release

**Comment by frenck** [comment]
@chpego Oh

**Comment by chpego** [comment]
Maybe you can fix it, do you want to open a new issue for that ? sorry to bother you

**Comment by frenck** [comment]
Closing this issue, as it is available on OpenVSX nowadays.
