### ISSUE TITLE
Hint on objects from Home Assistant does not work without "restarting" the extension

### ISSUE THREAD

**Issue by Beduir** [keesschollaart81/vscode-home-assistant#82]
Hint on objects from Home Assistant does not work without "restarting" the extension.
Writes "no suggestion".
It does not try to connect to the Home Assistant.
If I open the properties of an extension, disable it and then enable it again, everything will start working until the next VSCode restart.
OS: Windows 10
VSCode: 1.37.0
Extension: 1.0.2
![screen](https://user-images.githubusercontent.com/2959300/63063403-adf9c300-bf26-11e9-809f-76c5203a5ed7.png)

**Comment by keesschollaart81** [comment]
From what I can see from the screenshot you've only opened a single file. This extension only works when you open a workspace/folder with the whole configuration. So when you open a folder with configuration.yaml in the root all features should work and logging can be found here:

![image](https://user-images.githubusercontent.com/6755359/64485907-7aa90c00-d226-11e9-84d7-e183dcae7350.png)

I'm sorry if you'd expected this to work with a single file (it's not). If I misunderstood you feel free te reopen / provide additional details!
