### ISSUE TITLE
Update to wiki

### ISSUE THREAD

**Issue by eugeneniemand** [keesschollaart81/vscode-home-assistant#846]
I use a Raspberry PI and VS Code Remote SSH with this add on and it works fine. Here is how I did my config.

![image](https://user-images.githubusercontent.com/6813309/100606831-eaab2280-3301-11eb-8b0a-f147e5cb8f0e.png)

I could not submit a PR for the wiki

**Comment by dekiesel** [comment]
![image](https://user-images.githubusercontent.com/17333827/105559060-79d82380-5d10-11eb-8e1e-70a9fcdcf4f0.png)
It doesn't work for me unfortunately. 

I am working on an ubuntu machine connecting to HA on a raspberry pi. Any ideas maybe?
