### ISSUE TITLE
Show if an entity is not defined/used

### ISSUE THREAD

**Issue by nelbs** [keesschollaart81/vscode-home-assistant#878]
I was thinking if is possible to show 'dead' entities which are not exist anymore? 

Sometimes when I change or add some yaml code I forget to change all occurrences of a specific entity. I want to keep a clean script without unwanted leftovers I am looking for a way to localize them.  

Is this idea worth adding?

**Comment by frenck** [comment]
Duplicate of #251

**Comment by nelbs** [comment]
after I submit my idea I noticed that someone else did the same :-)
