### ISSUE TITLE
Feature Request: Goto Definition for Secrets

### ISSUE THREAD

**Issue by ed-holland** [keesschollaart81/vscode-home-assistant#90]
Use "goto Definition" to jump the the correct position in the secrets.yaml file. Alternatively if it does not exist, create it and allow it to be filled.

**Comment by foxsam21** [comment]
Also to add to the syntax checker from secrets if feasible. As in this screen-shot:
![secret_syntax](https://user-images.githubusercontent.com/11862524/67452740-31542680-f5f2-11e9-86aa-f06a427e8ba3.png)
In secrets.yaml it says metric...

**Comment by frenck** [comment]
Took a while, but picked this one up: https://github.com/keesschollaart81/vscode-home-assistant/pull/3576
