### ISSUE TITLE
HTTPS configuration

### ISSUE THREAD

**Issue by nickelnine** [keesschollaart81/vscode-home-assistant#900]
Please include the related YAML code:

```YAML
your:
   - yaml
```

Find my Home Assistant Configuration here:
[Link to Home Assistant Configuration](<link to repo here>)

Extension runs in:
- [] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [X] Other: Docker 

I'm running VS Code on:
- [ ] Windows 
- [] Mac 
- [X] Linux 

I'm accessing my files:
- [X] From local disk 
- [ ] Via remote SSH 
- [ ] Smb
- [ ] Other:  

Today I configured SSL for my Home Assistant instance but now the extension cannot connect to it. I created a new token and used IP address and hostname in the Host URL but nothing is validating.

Any help is appreciated.

![image](https://user-images.githubusercontent.com/28116390/102828094-0eadd100-43a1-11eb-96d9-f940a40930c7.png)

**Comment by frenck** [comment]
Any errors in the extension output logs?

**Comment by nickelnine** [comment]
Yes...
```
Connecting to Home Assistant...
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant... Tries left: 3
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
Connected to Home Assistant
WebSocket Connection to Home Assistant closed with an error: Disconnected from Home Assistant with a WebSocket error with message: Unexpected server response: 522
```

**Comment by frenck** [comment]
`522` is a connection timeout.
Is the SSL certificate a valid one from the connection endpoint of the extension? Or is it self-signed?

**Comment by nickelnine** [comment]
It's an origin certificate I created from Cloudflare.

**Comment by frenck** [comment]
2096, is not a standard port, so you are not connecting via Cloudflare in this case? This means, the certificate won't validate fully.

**Comment by nickelnine** [comment]
I am connecting to my HA instance via Cloudflare through the `subdomain.domain` I defined. According to Cloudflare, 2096 is an HTTPS port they support although it may not generally be standard (not sure, just going by their docs!).

![image](https://user-images.githubusercontent.com/28116390/102830497-a9f57500-43a6-11eb-8f93-79bc407c77f1.png)

**Comment by frenck** [comment]
Oh right, strange... in that case, it should just work 😟

**Comment by nickelnine** [comment]
No, that does not work either.
Connecting to HA via my local IP address port 2096 (same change to extension Host Url), at first the extension logs a successful connection but my VSCode panel in HA is blank. 
```
Connecting to Home Assistant...
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant... Tries left: 3
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
Connected to Home Assistant

```
Logging out of HA and logging back in, the extension logs errors:
```
WebSocket Connection to Home Assistant closed with an error: Disconnected from Home Assistant with a WebSocket error with message: connect ETIMEDOUT 192.0.0.168:2096
[Auth Phase] Connecting to Home Assistant... Tries left: 2
WebSocket Connection to Home Assistant closed with an error: Disconnected from Home Assistant with a WebSocket error with message: connect ETIMEDOUT 192.0.0.168:2096
[Auth Phase] Connecting to Home Assistant... Tries left: 1
```

**Comment by nickelnine** [comment]
I reverted to connecting with Cloudflare, restarted the VSCode container, and now the extension output logs:
```
[Home Assistant Language Server(339)] Started and initialize received
Connecting to Home Assistant...
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant... Tries left: 3
Applying schemas to 11 of your configuration files...
Schemas updated!
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
Connected to Home Assistant
```
But when I open HA, the VSCode panel is still blank. Don't know what else to do from here.

**Comment by tomukasteris** [comment]
I get the same problem as well. I use certificate from IONOS. Certificate itself is fine. Any resolution to fix it?

`Error connecting to your Home Assistant Server at https://raspberrypi.domain.co.uk:8123 and token 'eyJ0e...', check your network or update your VS Code Settings, make sure to (also) check your workspace settings! Error: ERR_CANNOT_CONNECT`

**Comment by hellcry37** [comment]
same issue
