### ISSUE TITLE
Correct indentation support

### ISSUE THREAD

**Issue by DarkPark** [keesschollaart81/vscode-home-assistant#93]
Please do not ignore current indentation options (4 spaces) and not always force 2 spaces.

**Comment by keesschollaart81** [comment]
You're right! WIth the next version you'll be able to update the default tabSize (2) using the settings:
```json
{
    "editor.tabSize": 7
}
```

**Comment by DarkPark** [comment]
thank you for your work! looking forward to it :)

**Comment by keesschollaart81** [comment]
Note to future self: Remeber that this tabSize property is overwritten by VS Code because this value is auto detected. To disable this behaviour set `editor.detectIndentation` to false.
