### ISSUE TITLE
Preview Material Design Icons

### ISSUE THREAD

**Issue by rkaramandi** [keesschollaart81/vscode-home-assistant#960]
Not sure if this is even possible or supported by VSCode, but it would be amazing to get some sort of a Material Design Icon (mdi) viewer as part of this plugin. 

For example, if I have `mdi:apple` for an icon, it shows up the apple icon in a preview (so I'm validating that I'm using the right icon or even the right name and don't have a typo).

**Comment by frenck** [comment]
I would highly recommend installing: <https://marketplace.visualstudio.com/items?itemName=lukas-tr.materialdesignicons-intellisense>

As that provides all of that (including inline previews, search and auto-completion). 👍

**Comment by rkaramandi** [comment]
Ooh that might work actually :) Nevermind on this request then! 

Thanks Franck!!

**Comment by frenck** [comment]
No problem 😄
